const stops = [
  {name:"Bliss Park Playground", address:"Bliss Park Playground, Longmeadow", title:"The stolen staff", story:"At 9:00 AM, Mr. Potato Head is missing the ancient Staff of Ministry. Mrs. Orac believes a rogue historian stole it to break Longmeadow’s protection spell. Your job: follow the thief’s historical trail before sundown.", clue:"Study both sides of the cryptic note at the playground. Find the star—and its number—to uncover the first direction.", hint:"Examine the back of the note closely. It points directly toward your first destination."},
  {name:"Life Sculpture", address:"588 Longmeadow St", title:"A fallen tree’s second life", story:"Harold Grinspoon began sculpting after a cherry tree fell in his yard. His 25-foot Life sculpture turns reclaimed wood into a landmark—and a perfect place for the thief’s next signal.", clue:"Look at the stars and intersecting lines on the clue. Compare their shapes with the sculpture and the view around it.", hint:"The floating stars and crossing lines are intentional. Let the real-world scene complete the puzzle."},
  {name:"Storrs Library", address:"693 Longmeadow St", title:"Portraits of the past", story:"Sarah Williams Storrs’ gift created the Storrs Library Association. The original Storrs House moved in 1932, but Reverend Richard Salter Storrs and his family remain present inside.", clue:"Find the four family portraits in the library—or use the portrait resource if the library is closed. Read their details as a set.", hint:"There are four portraits. Their shared details, rather than a single portrait, lead onward."},
  {name:"First Church of Christ", address:"763 Longmeadow St", title:"The panicked groom", story:"Longmeadow’s first minister was Reverend Stephen Williams. The church was moved from the Green in 1873, and its 1809 bell came from Paul Revere. A groom hands you two enigmatic papers before dashing off to find his bride.", clue:"Use the pair of papers to solve the house number on Williams Street.", hint:"Treat both papers as parts of one message. The historical details may tell you which features matter."},
  {name:"Second Town Hall", address:"20 Williams St", title:"A civic code", story:"Town meetings began on the Green, moved to an 1873 schoolhouse, then to this Colonial Revival town hall in 1930, and finally to Greenwood Center in 2024. A clue waits in the bench frame.", clue:"Match the symbols on the slip of paper to the scroll pediment above the main door to reveal a word.", hint:"Look up at the main-door pediment, then compare the visible symbols with the clue one by one."},
  {name:"Ann Scibelli Memorial", address:"Near 134 Williams St, between Williams St and Parkside Dr", title:"Nine lines", story:"At Ann Scibelli’s memorial, a colorful paper is tucked between two pavers. Its pattern is more method than decoration.", clue:"Use the clue’s line-position labels with the memorial’s nine lines of text to extract the next destination.", hint:"There are exactly nine memorial lines and nine positions on the clue. That correspondence is the key."},
  {name:"Razzmatazz Kids", address:"803 Williams St", title:"The ding-ding clue", story:"A woman tosses a note in front of Razzmatazz, calls “Ding-ding!”, and vanishes. The employee needs you to find the hidden four-letter word.", clue:"Read the note with the “Ding-ding!” moment in mind. Search for the four-letter word concealed in the pattern.", hint:"Say the clue aloud and consider sounds, repetitions, and pairs—not just what the marks look like."},
  {name:"Longmeadow Shops", address:"North side of Bliss Rd", title:"The final Polaroids", story:"An old-fashioned photographer says that storefronts can be read like history. Her Polaroids contain the final test—and the route to the Staff of Ministry.", clue:"Identify the businesses shown in the Polaroids. Take the requested letters from those shop names to decode the final answer.", hint:"Start by naming each storefront feature. The clue tells you how to choose the letters once each name is known."}
];
const key="staff-of-ministry-progress"; let state=JSON.parse(localStorage.getItem(key)||'{"unlocked":0,"done":[]}');
const save=()=>localStorage.setItem(key,JSON.stringify(state)); const app=document.querySelector('#app');
function head(){return `<header class="mast"><div class="sigil">✦</div><div><p class="eyebrow">Longmeadow outdoor mystery</p><h1>The Staff of Ministry</h1></div></header>`}
function home(){let complete=state.done.length; app.innerHTML=`<div class="shell">${head()}<section class="card hero"><span class="tag">8 stops</span><span class="tag">~4 miles</span><span class="tag">Works offline</span><h2>Save the town before sundown.</h2><p>A self-guided historical mystery trail through Longmeadow. Your progress is kept on this device—even with no signal.</p><button class="button gold" onclick="showStop(${Math.min(state.unlocked,7)})">${complete?"Continue adventure":"Begin the investigation"}</button></section><section class="card"><h2>Before you go</h2><ul><li>Start at Bliss Park Playground; bikes or scooters are helpful.</li><li>Bring a charged phone, pencil, and paper.</li><li>Stay on sidewalks, watch traffic, and respect private property.</li><li>Open this app once while online, then add it to your home screen for offline play.</li></ul><p class="notice"><strong>Home-screen install:</strong> On iPhone, use Share → Add to Home Screen. On Android, use the browser menu → Install app.</p></section><section class="card"><div class="topline"><h2>Case progress</h2><span>${complete}/8 solved</span></div><div class="progress"><i style="width:${complete/8*100}%"></i></div><div class="route">${stops.map((s,i)=>`<button class="stop ${state.done.includes(i)?'done':''}" ${i>state.unlocked?'disabled':''} onclick="showStop(${i})"><span class="num">${state.done.includes(i)?'✓':i+1}</span><span><strong>${s.name}</strong><small>${s.address}</small></span></button>`).join('')}</div></section>${complete===8?`<button class="button ghost full" onclick="resetGame()">Start a new investigation</button>`:''}</div>`}
function showStop(i){let s=stops[i];app.innerHTML=`<div class="shell">${head()}<div class="topline"><button class="button ghost" onclick="home()">← Case map</button><span class="small">Stop ${i+1} of 8</span></div><div class="progress"><i style="width:${i/8*100}%"></i></div><article class="card chapter"><p class="eyebrow">${s.address}</p><h2>${s.title}</h2><p class="location">📍 ${s.name}</p><p>${s.story}</p><div class="clue"><h3>🔎 Your clue</h3><p>${s.clue}</p></div><details class="hint"><summary>Need a nudge? Open hint</summary><p>${s.hint}</p></details><div class="answer"><input id="note" placeholder="Optional: save your answer / notes" value="${(state.notes||{})[i]||''}"/><button class="button" onclick="solve(${i})">${i===7?'Recover the staff':'I solved it →'}</button></div><p class="small">Answers are saved only on this device. Choose “I solved it” when your team is ready to move on.</p></article></div>`}
function solve(i){state.notes||={};state.notes[i]=document.querySelector('#note').value;if(!state.done.includes(i))state.done.push(i);state.unlocked=Math.max(state.unlocked,Math.min(i+1,7));save();if(i===7) finale();else home()}
function finale(){app.innerHTML=`<div class="shell">${head()}<section class="card complete"><div class="sigil">✦</div><p class="eyebrow">Case closed</p><h2>The Staff is safe.</h2><p>You followed Longmeadow’s history, solved the thief’s trail, and restored the town’s protection. The Green is safe—for now.</p><button class="button" onclick="home()">View your case map</button></section></div>`}
function resetGame(){state={unlocked:0,done:[],notes:{}};save();home()} window.home=home;window.showStop=showStop;window.solve=solve;window.resetGame=resetGame;home();
if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js");
