/* Consolidated chapter revision: this file is loaded last and owns the player-facing flow. */
(()=>{
const F=(s,l)=>`<figure><img src="${s}" alt="${l}"><figcaption>${l}</figcaption></figure>`, G=(...x)=>`<section class="gallery">${x.join('')}</section>`, nav=n=>`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter ${n+1} of 8</span></div>`;
const H=JSON.parse(localStorage.getItem('staff-ministry-final-hints')||'{}'), keep=()=>localStorage.setItem('staff-ministry-final-hints',JSON.stringify(H)), bottom=()=>requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'auto'}));
const finish=n=>{if(!S.d.includes(n))S.d.push(n);S.u=Math.max(S.u,Math.min(7,n+1));save()};
const answers={1:'library',2:'church',3:'20',4:'racecar',5:'shops',6:'tram',7:'icecream'}, solutions={1:'Storrs Library',2:'First Church of Christ',3:'20 Williams Street',4:'RACECAR',5:'SHOPS',6:'TRAM',7:'ICE CREAM'};
const hints={
1:['<strong>Hint #1: Focus on the shapes</strong><br>The clue has floating stars and intercepting lines. Look carefully at how those shapes interact with the sculpture.','<strong>Hint #2: Alignment is key</strong><br>Some stars align perfectly with circular orbs while others are off-center. The lines show where branches cross.','<strong>Hint #3: Filter out the noise</strong><br>Read only the letters attached to stars that align with an orb.','<strong>Hint #4: Where to next?</strong><br>The correctly aligned stars spell a seven-letter physical destination.','<strong>Hint #5: The solved puzzle</strong><br>You now have enough information to identify the next destination.'],
2:['<strong>Hint #1: Who is who?</strong><br><ul><li>Reverend Richard Salter Storrs (1763–1819) wears an older 18th-century style black clerical robe with white collar tabs.</li><li>Reverend Richard S. Storrs of Brooklyn (1821–1900) has prominent white mutton-chop sideburns.</li><li>Mary Elwell (Jenks) Storrs (1824–1898), wife of Reverend Richard S. Storrs of Brooklyn, is the elegant woman in the gold frame.</li><li>Professor Richard S. Storrs (1830–1884) wears a 19th-century suit. His portrait is in black and white.</li></ul>You can get more information on the library page: <a href="https://longmeadowlibrary.org/history/" target="_blank" rel="noopener">longmeadowlibrary.org/history</a>','<strong>Hint #2: Use the clue left behind by the strange lady</strong><br>After identifying each person, find that family member’s red letter on the Storrs family-tree clue.','<strong>Hint #3: Put the letters in the correct order</strong><br>Work from left to right. You now have enough information to identify the next destination.'],
3:['<strong>Hint #1: Where do I start?</strong><br>The answers can be found at red-star houses, street signs with the town seal, the Green behind the war memorials, witness stones, and the Plaques on War memorial.','<strong>Hint #2: Some visual clues</strong>','<strong>Hint #3: What are the T/F answers?</strong><br>1T, 2T, 3T, 4F, 5T, 6F, 7F, 8F, 9F.','<strong>Hint #4: Now what?!</strong><br>Use the correct answers to connect the dots. Pay attention to number and color pairs.','<strong>Hint #5: How do I connect the dots?</strong><br>Start with the green dot marked 1, then continue through all nine dots.','<strong>Hint #6: The solved puzzle</strong><br>You now have enough information to identify the house number on Williams Street.'],
4:['<strong>Hint #1: Where do I need to look?</strong><br>Look up at the scroll pediment above the main door. Match its symbols to the slip of paper.','<strong>Hint #2: A common palindrome</strong><br>Look closely at the stonework from left to right. Your eyes will pass a stylized pineapple, an elegant scroll flourish, a rosette, and a central flame finial, before mirroring back down through another rosette, scroll flourish, and pineapple. Match the letters to these symbols in the exact order you found them to uncover a hidden palindrome!','<strong>Hint #3</strong><br>The sequence reads the same in either direction.','<strong>Hint #4: Solved puzzle</strong><br>You now have enough information to identify the palindrome.'],
5:['<strong>Hint #1: Lines</strong><br>There are exactly 9 lines of text engraved into the memorial plaque and 9 line positions* mentioned on the clue left by the thief.<br><br><em>*Look closely on the left side of the clue for the “line position” label.</em>','<strong>Hint #2: Words</strong><br>Cross-reference a line number with a word position to find a word from the stone. For example, Line 1, Word 2 is <strong>PLACE</strong>.','<strong>Hint #3: Letters</strong><br>The number inside each colored square tells you which letter to extract from its word.','<strong>Hint #4: Colors</strong><br>Arrange the letters using the color order: <strong>PINK, SALMON, GREEN, YELLOW, BLUE.</strong>'],
6:['<strong>Hint #1</strong><br>Notice the colors and patterns on the note. Look around—and higher up—for the same design details.','<strong>Hint #2</strong><br>Compare the visual clue with details around Razzmatazz.','<strong>Hint #3</strong><br>Think about the “Ding-Ding!” sound. What historical vehicle made that famous ringing sound?','<strong>Hint #4</strong><br>Before cars, electric streetcars ran through Longmeadow. What is another four-letter word for a trolley?'],
7:['<strong>Hint #1: Look around</strong><br>Identify the stores or businesses shown in the Polaroids.','<strong>Hint #2: Focus on letters</strong><br>Use the number on each Polaroid to choose one letter from each business name.','<strong>Hint #3: An example</strong><br>The CHICO logo has the number 3, so take its third letter: <strong>I</strong>.','<strong>Hint #4: The Polaroid answers</strong><br>CHICO (3rd: I); Urgent Care (7th: C); McKenna &amp; Caban (4th: E); CVS (1st: C); Warby Parker (3rd: R); Fleet Feet (3rd: E); Delaney (4th: A); Max Burger (1st: M).']};
const hintArt={1:{1:[['asset-original-assets-chapter-2-7.jpg','The clue and the sculpture']],4:[['asset-original-assets-chapter-2-8.jpg','Map to Storrs Library']]},3:{1:[['asset-original-assets-chapter-4-7.jpg','Some visual clues']]},4:{0:[['asset-original-assets-chapter-5-6.jpg','The scroll pediment at 20 Williams Street']]},6:{1:[['asset-original-assets-chapter-7-6.jpg','Razzmatazz Kids storefront sign']],3:[['asset-original-assets-chapter-7-7.jpg','The Longmeadow trolley']]}};
function hintBox(n){let c=H[n]||0, shown=hints[n].slice(0,c).map((h,i)=>`<p>${h}</p>${hintArt[n]?.[i]?G(...hintArt[n][i].map(a=>F(...a))):''}`).join(''), ctl=c<hints[n].length?`<button class="button ghost full" onclick="finalHint(${n})">${c?'Show another hint':'I need a hint'}</button>`:`<button class="button ghost full" onclick="finalSolution(${n})">Just show me the solution!</button>`;return `<section class="hint-progress">${shown}${ctl}</section>`}
window.finalHint=n=>{H[n]=Math.min((H[n]||0)+1,hints[n].length);keep();chapter(n);bottom()}; window.finalSolution=n=>{H['s'+n]=true;keep();chapter(n);bottom()};
function answer(n,label){app.innerHTML=wrap(`<section class="card answer"><p class="eyebrow">Submit your answer</p><h2>${label}</h2><input id="solution" class="solution" autocomplete="off" placeholder="Your answer"><button class="button full" onclick="finalCheck(${n})">Submit answer</button><p id="feedback" class="small"></p><button class="button ghost" onclick="chapter(${n})">← Back to puzzle</button></section>`)}
function screen(n,body,images,question){const loc=['','Start at the Harold Grinspoon’s ‘Life’ sculpture.','Start at the Storrs Library.','Start at the First Church of Christ.','Start at 20 Williams Street.','Start at the Ann Scibelli’s Memorial.','Start at the Razzmatazz Kids toy store.','Start at the Longmeadow Shops — North side of Bliss Road.'][n],sol=H['s'+n]?`<p class="solution-reveal"><strong>Solution: ${solutions[n]}</strong></p>${n===4?G(F('c5-1.jpg','Solved puzzle')):n===2?G(F('asset-chapter3-clue-back.jpg','Solved puzzle')):''}`:'';app.innerHTML=wrap(`${nav(n)}<article class="card chapter original"><p class="location">📍 ${loc}</p>${body}${G(...images.map(a=>F(...a)))}<section class="answer"><h3>${question}</h3><button class="button full" onclick="finalAnswer(${n})">Yes! I know the answer.</button>${hintBox(n)}${sol}</section></article>`) }
function two(){screen(1,`<h3>The Harold Grinspoon ‘Life’ Sculpture</h3><p>In his mid-80s, renowned local businessman and philanthropist <strong>Harold Grinspoon</strong> began a third career as an artist after a large cherry tree fell in his Longmeadow backyard. He transformed its organic form into a striking 25-foot outdoor sculpture.</p><p>As Mrs. Orac predicted, you spot <strong>the clue left behind by the thief</strong> right in front of the magnificent sculpture.</p>`,[['asset-original-assets-chapter-2-3.jpg','Harold Grinspoon ‘Life’ Sculpture'],['asset-original-assets-chapter-2-5.jpg','The view from where the clue was left'],['asset-original-assets-chapter-2-4.jpg','The clue left behind by the thief']],'Do you know where the clue is pointing next?')}
function threeStart(){app.innerHTML=wrap(`${nav(2)}<article class="card chapter original"><p class="location">📍 Start at the Storrs Library.</p><h3>Welcome to Storrs Library!</h3><p>In 1907, <strong>Sarah Williams Storrs</strong> donated the Storrs Estate and property in her will. This led to the Richard Salter Storrs Library Association in 1910.</p><p>While the library has changed locations, the presence of Reverend Richard Salter Storrs and several family members can still be felt inside.</p>${G(F('asset-chapter3-library.jpg','The Storrs Library'))}<section class="answer"><h3>Are you able to enter the library and look for the family portraits?</h3><button class="button full" onclick="finalC3Clue()">Yes, I can enter the library.</button><button class="button ghost full" onclick="finalPortraits()">No, the library is closed.</button></section></article>`) }
function threeClue(){let sol=H.s2?`<p class="solution-reveal"><strong>Solution: First Church of Christ</strong></p>${G(F('asset-chapter3-clue-back.jpg','Solved puzzle'))}`:'';app.innerHTML=wrap(`${nav(2)}<article class="card chapter original"><h3>Good job! You have located the four portraits.</h3><p>A librarian approaches and hands you <strong>a folded slip of paper</strong> left by a mysterious woman for anyone examining the portraits.</p>${G(F('asset-chapter3-librarian.jpg','The librarian'),F('asset-chapter3-clue-front.jpg','Folded slip of paper (front)'),F('asset-chapter3-clue-back.jpg','Folded slip of paper (back)'))}<button class="button ghost full" onclick="finalPortraits()">View the portraits</button><section class="answer"><h3>Did you uncover your next destination?</h3><button class="button full" onclick="finalAnswer(2)">Yes! I know the answer.</button>${hintBox(2)}${sol}</section></article>`)}
function portraits(){app.innerHTML=wrap(`${nav(2)}<article class="card chapter original"><h3>The portraits inside the library</h3>${G(F('asset-chapter3-portrait-1.jpg','Portrait #1'),F('asset-chapter3-portrait-2.jpg','Portrait #2'),F('asset-chapter3-portrait-3.jpg','Portrait #3'),F('asset-chapter3-portrait-4.jpg','Portrait #4'))}<button class="button full" onclick="finalC3Clue()">Continue to the clue</button></article>`)}
function four(){screen(3,`<h3>The First Church</h3><p>The church’s first minister, Reverend Stephen Williams, settled here in 1716. Its 1768 building was moved to this location in 1873, and its bell was purchased directly from Paul Revere in 1809.</p><h3>The panicked groom</h3><p>A man in a sharp tuxedo hands you <strong>two enigmatic papers</strong>. He is getting married today and has lost his bride.</p>`,[['asset-original-assets-chapter-3-11.jpg','Location of the First Church of Christ'],['asset-original-assets-chapter-3-12.jpg','First Church of Christ'],['asset-original-assets-chapter-4-8.jpg','The two enigmatic papers']],'Do you know where to go next?')}
function five(){screen(4,`<h3>The Second Town Hall</h3><p>You arrive at <strong>20 Williams Street</strong>, a Colonial Revival building that served as Longmeadow’s Town Hall before the move to Greenwood Center.</p><p>A <strong>slip of paper wedged into the bench frame.</strong> A new puzzle awaits…</p>`,[['asset-original-assets-chapter-5-1.jpg','Location of the 20 Williams Street'],['asset-original-assets-chapter-5-4.jpg','20 Williams Street'],['asset-original-assets-chapter-5-3.jpg','The puzzle clue']],'Did you solve the puzzle?')}
function six(){screen(5,`<h3>A Place to Rest, Reflect and Renew</h3><p>You are now standing in front of Ann Scibelli's memorial stone. Ann was a beloved member of the Longmeadow community. Looking around, you notice a small, <strong>colorful piece of paper</strong> wedged neatly between two pavers. You carefully pull it free and examine it. What could that mean? You pull out your notebook, study the pattern, and start putting the pieces together...</p>`,[['asset-original-assets-chapter-6-1.jpg','Location of Ann Scibelli’s Memorial'],['asset-original-assets-chapter-6-2.jpg','Ann Scibelli’s Memorial'],['asset-original-assets-chapter-5-12.jpg','The memorial stone'],['c6-1.jpg','Piece of paper found between two pavers (front)'],['c6-2.jpg','Piece of paper found between two pavers (back)']],'Did you crack the code and know where to go next?')}
function seven(){screen(6,`<h3>The Ding-Ding clue!</h3><p>You arrive at Razzmatazz, where an employee holds a mysterious slip of paper. An eccentric woman tossed it into the air and shouted <strong>“Ding-Ding!”</strong> before disappearing.</p>`,[['asset-original-assets-chapter-7-1.jpg','Location of Razzmatazz Kids'],['asset-original-assets-chapter-7-2.jpg','Razzmatazz Kids storefront'],['asset-original-assets-chapter-7-4.jpg','The toy store employee'],['asset-original-assets-chapter-7-5.jpg','The Ding-Ding clue']],'Did you find the four-letter word hidden behind the clue?')}
function eight(){screen(7,`<h3>The Strange Photographer</h3><p>You arrive at the Longmeadow Shops and spot a lady taking photographs with an old-fashioned Polaroid camera.</p><p>She hands you <strong>a stack of pictures</strong>. This is <strong>your final test</strong>: solve the puzzle to retrieve the Staff of Ministry and save Longmeadow.</p>`,[['asset-original-assets-chapter-8-1.jpg','Location of the Longmeadow Shops on the North side of Bliss Road'],['asset-original-assets-chapter-8-2.jpg','The Longmeadow Shops'],['asset-original-assets-chapter-8-4.jpg','The photographer'],['asset-original-assets-chapter-8-5.jpg','The stack of Polaroids']],'Did you decode your last clue?')}
const one=window.chapter; window.chapter=n=>n===0?one(0):n===1?two():n===2?threeStart():n===3?four():n===4?five():n===5?six():n===6?seven():eight(); window.finalAnswer=n=>answer(n,n===4?'The answer to the puzzle is…':n===5?'I have cracked the code and found the word. It is…':n===7?'What is the FINAL answer?':'What is your answer?'); window.finalC3Clue=threeClue;window.finalPortraits=portraits;
window.finalCheck=n=>{let v=(document.querySelector('#solution')?.value||'').toLowerCase().replace(/[^a-z0-9]/g,'');if(!v.includes(answers[n])){document.querySelector('#feedback').textContent='Incorrect. Review the clue and hints, then try again.';return}if(n===4)return racecar();complete(n)};
function racecar(){app.innerHTML=wrap(`${nav(4)}<article class="card chapter original"><h2>Correct! Racecar?! Race car?! What in the world could that mean?</h2><p>As you stand there scratching your head, a sudden, deafening roar echoes from behind the police station.</p><p>In a flash, a sleek race car screeches into view, its driver completely hidden behind pitch-black tinted windows. It zooms right past you, tears a sharp left onto Williams Street, and barrels toward the center of town. There is absolutely no way this is a coincidence — the clue you just decoded is unfolding right before your eyes!</p><p>You sprint after it, your heart pounding. While catching up to a speeding car is impossible, you spot a hand flash out of the driver window and toss something onto the pavement. Following the tire tracks down Williams Street, you find a crisp, handwritten note sitting on the sidewalk. You reach down and pick it up… your <strong>next clue</strong>.</p>${G(F('asset-original-assets-chapter-5-9.jpg','The clue left by the thief'))}<section class="answer"><h3>Did you find your next destination?</h3><button class="button full" onclick="racecarDone()">Yes! I know where to go next.</button><button class="button ghost full" onclick="racecarHint()">I need a hint.</button><section id="racecar-hint"></section></section></article>`)} window.racecarHint=()=>{let b=document.querySelector('#racecar-hint');if(b)b.innerHTML=G(F('asset-original-assets-chapter-5-10.jpg','Follow the race car down Williams Street.'),F('asset-original-assets-chapter-5-11.jpg','Ann Scibelli’s Memorial'));bottom()};window.racecarDone=()=>{finish(4);app.innerHTML=wrap(`<section class="card complete chapter original"><div class="sigil">✓</div><h2>Great! Head toward the Ann Scibelli’s Memorial to continue the adventure.</h2>${G(F('asset-original-assets-chapter-5-10.jpg','Location of the memorial'))}<p>The memorial is located near 134 Williams Street on a median area between Williams Street and Parkside Dr.</p><p>You are ready to move onto the next chapter.</p><button class="button full" onclick="map()">Open case map</button></section>`)};
function complete(n){finish(n);if(n===7)return ending();const data={1:['Correct! Head toward the library to continue the adventure.',G(F('asset-original-assets-chapter-3-1.jpg','Location of the Storrs Library'))],2:['Correct! Head toward the First Church of Christ to continue the adventure.',G(F('asset-original-assets-chapter-3-11.jpg','Location of the First Church of Christ'))],3:['Correct! Head toward 20 Williams Street to continue the adventure.',G(F('asset-original-assets-chapter-5-1.jpg','Location of the 20 Williams Street'))],5:['Correct!',`<p>As you head toward the center of town, your phone buzzes with an urgent <strong>text from Mrs. Orac</strong>: “Quick, go to Razzmatazz! A new cryptic note was just spotted outside the entrance!”</p>${G(F('asset-original-assets-chapter-7-9.jpg','Text message from Mrs. Orac'),F('asset-original-assets-chapter-7-1.jpg','Location of Razzmatazz Kids'))}`],6:['Correct!',`<p>Back in 1896, long before cars filled Route 5, electric trolleys (or trams) rattled straight down Longmeadow Street. Powered by overhead wires, these wooden streetcars were famous for the sharp “Ding! Ding!” of their brass foot-gongs.</p><p>Your thoughts wander to the past, imagining what it would have felt like to glide down Route 5 on an old electric tram with your friends. Suddenly, a panicked message from Mrs. Orac snaps you back to the present.</p>${G(F('asset-original-assets-chapter-7-7.jpg','The Longmeadow trolley'),F('asset-original-assets-chapter-7-9.jpg','Panicked message from Mrs. Orac'),F('asset-original-assets-chapter-8-1.jpg','Location of the Longmeadow Shops on the North side of Bliss Road'))}<p><strong>Head toward the Longmeadow Shops on the North side of Bliss Road.</strong></p>`]}[n];app.innerHTML=wrap(`<section class="card complete chapter original"><div class="sigil">✓</div><p class="eyebrow">ANSWER ACCEPTED</p><h2>${data[0]}</h2>${data[1]}<p>You are ready to move onto the next chapter.</p><button class="button full" onclick="map()">Open case map</button></section>`)}
function ending(){app.innerHTML=wrap(`<section class="card chapter original"><div class="sigil">✓</div><p class="eyebrow">FINAL ANSWER ACCEPTED</p><h2>Ice cream was the final clue!</h2><p><strong>Ice cream</strong> was the final clue! You head toward the local ice cream shop — <strong>Batch Ice Cream</strong> (682A Bliss Rd) — expecting to find the rogue historian ready to surrender the Staff of Ministry.</p><p>Instead, you find Mrs. Orac smiling ear-to-ear while enjoying a scoop. But she isn't just smiling because of the ice cream—she’s smiling because of <strong>you</strong>! Looking around, you spot the very race car you’d been chasing earlier, safely parked right out front. What in the world?!</p><p>As you stand there confused, Mrs. Orac invites you to take a seat and reveals the truth: <strong>it was all a test!</strong></p><p>The <strong>Staff of Ministry</strong> was pure fiction (though all the fascinating Longmeadow history you uncovered along the way was 100% real!). Longmeadow was never under the Curse of 1716, and there was no actual thief—just Mrs. Orac dropping clues all over town to test your skills!</p><p>As a member of the Underground Longmeadow Historical Society, she designed this challenge to recruit the sharpest minds in town—the Master Detectives Longmeadow can count on when real mysteries arise.</p><p>You’ve proven your brilliance, teamwork, and quick thinking. Take a bow—you are officially <strong>certified Underground Longmeadow Historical Society members!</strong></p>${G(F('asset-original-assets-chapter-8-6.jpg','Ice cream was the “coolest” reward in town!'),F('asset-original-assets-chapter-8-7.jpg','Your badge of honor!'),F('asset-original-assets-chapter-8-8.jpg','Your official certificate'))}<p>Thanks for playing! If you enjoyed the game and want to support our family in creating more local games, tips via Venmo are appreciated. Thank you so much.</p><a class="button full" href="https://www.venmo.com/u/CarohartMA" target="_blank" rel="noopener">Optional tip via Venmo</a><p>🌟 Loved the adventure? We'd love to hear your thoughts! Help others discover the outdoor escape game by leaving us a review on our Facebook Page.</p><a class="button full" href="https://www.facebook.com/5ofHeartsEscapeGames/reviews" target="_blank" rel="noopener">Leave a review</a><button class="button ghost full" onclick="home()">Return to the welcome page</button></section>`)}
const earlierR1Check=window.r1Check;window.r1Check=n=>{const value=(document.querySelector('#solution')?.value||'').toLowerCase().replace(/[^a-z]/g,'');if(n!=='johnny')return earlierR1Check(n);if(value!=='john'&&value!=='johnny'){const feedback=document.querySelector('#feedback');if(feedback)feedback.textContent='Incorrect. Review the hints and try again.';return}finish(0);app.innerHTML=wrap(`<section class="card complete chapter original"><div class="sigil">✓</div><p class="eyebrow">ANSWER ACCEPTED</p><h2>Correct! Johnny Appleseed once lived in this house!</h2><p>“Johnny Appleseed” (born John Chapman) was an American pioneer and nurseryman who became a legendary folk hero of the 19th century.</p>${G(F('asset-chapter1-new-johnny-appleseed.jpg','Johnny Appleseed'),F('asset-chapter1-new-orac-message.jpg','Message from Mrs. Orac'),F('asset-chapter1-new-grinspoon-map.jpg','Location of Harold Grinspoon’s sculpture'),F('asset-original-assets-chapter-2-3.jpg','Harold Grinspoon ‘Life’ Sculpture'))}<p>Head toward the sculpture to continue the adventure.</p><p>You are ready to move onto the next chapter.</p><button class="button full" onclick="map()">Open case map</button></section>`) };
const oldHome=window.home,oldMap=window.map;window.home=()=>{oldHome();document.querySelectorAll('a[href="https://www.venmo.com/u/CarohartMA"]').forEach(a=>a.textContent='Venmo')};window.map=()=>{oldMap();document.querySelectorAll('.stop small').forEach(x=>{if(x.textContent==='20 Williams')x.textContent='20 Williams Street';if(x.textContent==='Ann Scibelli’s memorial')x.textContent='Ann Scibelli’s Memorial'})};
const st=document.createElement('style');st.textContent='.chapter ul{padding-left:1.25rem}.chapter .location{font-weight:700}.chapter .solution-reveal{margin-top:1rem;padding:1rem;background:#f1f8ef;border-radius:.5rem}.chapter p{text-align:left}.chapter .sigil,.chapter .eyebrow,.chapter h2{text-align:center}';document.head.append(st);window.home();
})();

/* Chapter 1 hints are appended in place: one button press reveals one hint. */
(()=>{
  const c1=[
    '<strong>Hint #1: Examine the crime scene</strong><br>Take a close look at the back of the cryptic note left behind at Bliss Park. The message points straight to your very first destination!',
    '<strong>Hint #2: Go to the address mentioned in the back of the cryptic note.</strong><section class="gallery"><figure><img src="asset-chapter1-new-fairfield-map.jpg" alt="Location of Fairfield Terrace"><figcaption>Location of Fairfield Terrace</figcaption></figure></section>',
    '<strong>Hint #3: The address</strong><br>Look for the house located at 14 Fairfield Terrace.<section class="gallery"><figure><img src="asset-chapter1-new-fairfield-map.jpg" alt="Location of 14 Fairfield Terrace"><figcaption>Location of 14 Fairfield Terrace</figcaption></figure></section>'
  ];
  window.r1MoreC1Hint=()=>{
    const panel=document.querySelector('.hint-progress'); if(!panel)return;
    const shown=panel.querySelectorAll(':scope > p').length;
    if(shown>=c1.length)return;
    panel.insertAdjacentHTML('beforeend',`<p>${c1[shown]}</p>`);
    const control=panel.querySelector('button');
    if(shown+1>=c1.length){if(control)control.remove();}
    else if(control)control.textContent='Show another hint';
    requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'auto'}));
  };
})();

