const answerRules=[
  ['What is the star number?','76'],
  ['The clue indicates that the next destination is the…','library'],
  ['The next destination is the…','church'],
  ['What is the house number you need to go to on Williams Street?','20'],
  ['The answer to the puzzle is…','racecar'],
  ['I have cracked the code and found the word. It is…','shops'],
  ['The answer is…','tram'],
  ['What is the FINAL answer?','icecream']
];
function chapter(n){const c=C[n];const figures=Array.from({length:c[2]},(_,i)=>`<figure><img src="c${n+1}-${i+1}.jpg" alt="Original Chapter ${n+1} puzzle resource"><figcaption>Original game puzzle resource</figcaption></figure>`).join('');app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter ${n+1} of 8</span></div><article class="card chapter original"><p class="location">📍 ${c[0]}</p>${fmt(c[1])}<section class="gallery">${figures}</section><section class="answer"><h3>${c[3]}</h3><p>Have you solved the puzzle?</p><button class="button full" onclick="submitAnswer(${n})">Yes — submit our answer</button><details class="hint"><summary>No — I need a hint</summary><p>${fmt(c[4])}</p></details></section></article>`) }
function submitAnswer(n){const r=answerRules[n];app.innerHTML=wrap(`<section class="card answer"><p class="eyebrow">Submit your answer</p><h2>${r[0]}</h2><input id="solution" class="solution" autocomplete="off" placeholder="Your answer"><button class="button full" onclick="checkAnswer(${n})">Submit answer</button><p id="feedback" class="small"></p><button class="button ghost" onclick="chapter(${n})">← Back to puzzle</button></section>`)}
function checkAnswer(n){const entered=document.querySelector('#solution').value.toLowerCase().replace(/[^a-z0-9]/g,'');if(entered.includes(answerRules[n][1])){if(!S.d.includes(n))S.d.push(n);S.u=Math.max(S.u,Math.min(7,n+1));save();map()}else document.querySelector('#feedback').textContent='Incorrect. Review the clue and open the hint room, then try again.'}
window.chapter=chapter;window.submitAnswer=submitAnswer;window.checkAnswer=checkAnswer;

// Chapter 3 has an additional original-form decision before its main clue.
const standardChapter=chapter;
function chapterOneJohnny(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="chapter(0)">← Back to Chapter 1</button><span class="small">Chapter 1 of 8</span></div><article class="card chapter original"><h3>76 is right!</h3><p>You are now standing in front of one of the oldest houses in town.</p><p>Do you know the name of the boy who lived in the house with the numbered star during the late 18th century?</p><section class="answer"><button class="button full" onclick="submitJohnnyAnswer()">Yes — submit our answer</button><details class="hint"><summary>No — I need a hint</summary><p><strong>Hint #1: The Legend of the Fruit</strong><br>The boy who grew up in this house went on to travel far and wide across America, planting vast orchards of a crisp, delicious red fruit. Think of his famous nickname!</p><p><strong>Hint #2: The “Hat” Clue</strong><br>This folk hero wore a metal cooking pot on his head and became an iconic apple planter.</p><p><strong>Hint #3</strong><br>His legal name was John Chapman, but he is known by a six-letter nickname: J _ _ _ _ Y.</p></details></section></article>`) }
function submitJohnnyAnswer(){app.innerHTML=wrap(`<section class="card answer"><p class="eyebrow">Submit your answer</p><h2>What was the first name of the boy who grew up in the house with the numbered star in the late 18th century?</h2><input id="solution" class="solution" autocomplete="off" placeholder="6-letter first name / nickname"><button class="button full" onclick="checkJohnnyAnswer()">Submit answer</button><p id="feedback" class="small"></p><button class="button ghost" onclick="chapterOneJohnny()">← Back</button></section>`)}
function checkJohnnyAnswer(){const entered=document.querySelector('#solution').value.toLowerCase().replace(/[^a-z0-9]/g,'');if(entered.includes('johnny'))completeChapter(0);else document.querySelector('#feedback').textContent='Incorrect. Review the hint room, then try again.'}
function chapterFiveRacecar(){const figures=[9,10,11,12].map((n)=>`<figure><img src="asset-original-assets-chapter-5-${n}.jpg" alt="Original Chapter 5 follow-up resource"><figcaption>Original Chapter 5 resource</figcaption></figure>`).join('');app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="chapter(4)">← Back to Chapter 5</button><span class="small">Chapter 5 of 8</span></div><article class="card chapter original"><h3>Racecar?! Race car?! What in the world could that mean?</h3><p>A sudden, deafening roar echoes from behind the police station. A sleek race car screeches into view, its driver hidden behind pitch-black tinted windows. It tears a sharp left onto Williams Street and barrels toward the center of town.</p><p>You spot a hand flash out of the driver window and toss something onto the pavement. Following the tire tracks down Williams Street, you find a crisp handwritten note sitting on the sidewalk: your next clue.</p><section class="gallery">${figures}</section><section class="answer"><h3>Did you find the location of your next test?</h3><button class="button full" onclick="completeChapter(4)">Yes — continue</button><details class="hint"><summary>No — I need a hint</summary><p>The place you are looking for is Ann Scibelli’s memorial, near 134 Williams Street on the median between Williams Street and Parkside Drive.</p></details></section></article>`) }
function chapterTwo(){const figures=Array.from({length:8},(_,i)=>`<figure><img src="asset-original-assets-chapter-2-${i+1}.jpg" alt="Original Chapter 2 resource"><figcaption>Original Chapter 2 resource</figcaption></figure>`).join('');app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 2 of 8</span></div><article class="card chapter original"><p class="location">📍 Harold Grinspoon ‘Life’ Sculpture</p><p>Good job completing Chapter 1 and welcome to Chapter 2!</p><p>Start at the Harold Grinspoon <strong>‘Life’</strong> sculpture.</p><h3>The Harold Grinspoon ‘Life’ Sculpture</h3><p>In his mid-80s, renowned local businessman and philanthropist Harold Grinspoon embarked on a third career as an artist, inspired quite by accident when a large cherry tree fell in his Longmeadow backyard. Captivated by its organic form, he chose to transform the fallen timber into a lasting work of art rather than discard it, resulting in a striking 25-foot outdoor sculpture. This initial spark launched a prolific artistic chapter. In the years since, he has produced over a hundred large-scale sculptures crafted from reclaimed trees, with many prominently installed in public spaces and institutions across Massachusetts and nationwide.</p><p>As you expected based on Mrs. Orac’s message, you spot a fresh clue left behind by the thief right in front of the magnificent sculpture.</p><section class="gallery">${figures}</section><section class="answer"><h3>Do you know where the clue is pointing next?</h3><button class="button full" onclick="submitAnswer(1)">Yes — submit our answer</button><details class="hint"><summary>No — I need a hint</summary><p><strong>Hint #1: Focus on the Shapes</strong><br>The clue left at the sculpture has two main elements: floating stars and intercepting lines. They aren’t just placed randomly. Try looking at how these two shapes interact with what you see in the real world.</p><p><strong>Hint #2: Alignment is Key</strong><br>Not all stars are created equal. Some stars perfectly align and overlap with the circular orbs, while others float completely off-center. The intercepting lines indicate where branches cross. Are you looking at the sculpture and clue from where the clue was found?</p><p><strong>Hint #3: Filtering Out The Noise</strong><br>Try filtering out the noise: what happens if you only look at the letters attached to stars that perfectly line up with an orb?</p><p><strong>Hint #4: Where to Next?</strong><br>The stars that perfectly align with the orbs spell a 7-letter word indicating your next physical destination. Read the letters from left to right.</p><p><strong>Hint #5: The solved puzzle</strong><br>Make your way to Storrs Library and see what you can find there.</p></details></section></article>`) }
function chapterThreeStart(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 3 of 8</span></div><article class="card chapter original"><p class="location">📍 Storrs Library</p><h3>Welcome to Storrs Library!</h3><p>In 1907, <strong>Sarah Williams Storrs</strong>—granddaughter of the town's second pastor, Richard Salter Storrs—donated the Storrs Estate and property in her will. This generous gift led to the establishment of the Richard Salter Storrs Library Association in 1910.</p><p>The initial home of the Richard Salter Storrs Library was established in the historic Storrs House at 697 Longmeadow Street. When the current library building was constructed in 1932, the historic house was physically moved a short distance to the south to make room for it, where it now serves as the Storrs House Museum and Archive for the Longmeadow Historical Society.</p><p>While the library has changed locations over the years, the presence of <strong>Reverend Richard Salter Storrs</strong> and several of his family members can still be felt inside.</p><section class="answer"><h3>Are you able to enter the library and look for the family portraits?</h3><button class="button full" onclick="chapterThreeClue()">Yes — we found the portraits</button><button class="button ghost full" onclick="showChapterThreePortraits()">No — show us the portraits</button></section></article>`) }
function showChapterThreePortraits(){const figures=[1,2,3,4].map((n,i)=>`<figure><img src="asset-original-assets-chapter-3-${n}.jpg" alt="Chapter 3 portrait ${i+1}"><figcaption>Portrait #${i+1}</figcaption></figure>`).join('');app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="chapterThreeStart()">← Back</button><span class="small">Chapter 3 of 8</span></div><article class="card chapter original"><h3>The portraits inside the library</h3><p>Use these portraits if you cannot enter the library. The clue will still require you to identify the Storrs family members.</p><section class="gallery">${figures}</section><button class="button full" onclick="chapterThreeClue()">Continue to the clue</button></article>`) }
function chapterThreeClue(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="chapterThreeStart()">← Back</button><span class="small">Chapter 3 of 8</span></div><article class="card chapter original"><h3>Good job! You have located the four portraits.</h3><p>As you wonder what to do with your newfound observations, a librarian notices you studying the portraits and approaches.</p><p>“Excuse me,” she says quietly. “A woman came in just before you did and asked me to give this piece of paper to anyone who was examining these portraits. She left in such a hurry that I didn't even have time to ask her any questions, but she insisted that you would need this.”</p><p>She hands you the folded slip of paper and leaves you to your investigation.</p><section class="answer"><h3>Did you uncover your next destination?</h3><button class="button full" onclick="submitAnswer(2)">Yes — submit our answer</button><details class="hint"><summary>No — I need a hint</summary><p><strong>Hint #1: Who is Who?</strong> Reverend Richard Salter Storrs (1763–1819) wears an older 18th-century black clerical robe with white collar tabs. Reverend Richard S. Storrs of Brooklyn (1821–1900) has prominent white mutton-chop sideburns. Mary Elwell (Jenks) Storrs is the elegant woman in the gold frame. Professor Richard S. Storrs wears a 19th-century suit and is in black and white.</p><p><strong>Hint #2:</strong> After identifying the people, use the red letters associated with them on the Storrs family-tree clue. Read the portraits from left to right.</p></details></section></article>`) }
function chapterFour(){const figures=Array.from({length:10},(_,i)=>`<figure><img src="asset-original-assets-chapter-4-${i+1}.jpg" alt="Original Chapter 4 resource"><figcaption>Original Chapter 4 resource</figcaption></figure>`).join('');app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 4 of 8</span></div><article class="card chapter original"><p class="location">📍 First Church of Christ</p><p>Good job completing Chapter 3 and welcome to Chapter 4!</p><h3>The First Church</h3><p><strong>The First Pastor’s Captivity:</strong> Long before the current building rose, the church’s first minister was Reverend Stephen Williams, who settled here in 1716. As a young boy, Williams survived the 1704 Deerfield raid and was marched to Canada before being ransomed.</p><p><strong>The Human Alarm Clock:</strong> Before the church got its first bell in 1743, Longmeadow paid Nathaniel Burt 10 shillings a year to walk the street beating a drum to announce services.</p><p><strong>The Great Building Migration:</strong> The current 1768 structure originally stood on the Green, where the flagpole is today. In 1873, the entire church was moved to its present location.</p><p><strong>A Paul Revere Connection:</strong> The congregation purchased a replacement bell directly from Paul Revere in Boston in 1809.</p><h3>The panicked groom</h3><p>You are standing in front of the big white church when a man in a sharp tuxedo approaches you in a total panic. A strange woman shoved two enigmatic papers into his hands; he is getting married and has lost his bride. He gives you the papers so he can search for her.</p><section class="gallery">${figures}</section><section class="answer"><h3>Do you know where to go next?</h3><button class="button full" onclick="submitAnswer(3)">Yes — submit our answer</button><details class="hint"><summary>No — I need a hint</summary><p><strong>Hint #1: Where do I start?</strong><br>Find the true/false answers at red-star houses, street signs with the town seal, the Green behind the war memorials, the witness stones, and the memorial plaques.</p><p><strong>Hint #3: What are the T/F answers?</strong><br>1T, 2T, 3T, 4F, 5T, 6F, 7F, 8F, 9F.</p><p><strong>Hint #4: Now what?!</strong><br>Use the correct answers to connect the dots. Pay attention to the number and color pairs.</p><p><strong>Hint #5: How do I connect the dots?</strong><br>Statement 1 is true, so start with the green dot marked 1, then use the green dot marked 2, and continue through all nine dots to reveal the solution.</p></details></section></article>`) }
chapter=function(n){return n===1?chapterTwo():n===2?chapterThreeStart():n===3?chapterFour():standardChapter(n)};
window.chapter=chapter;window.chapterTwo=chapterTwo;window.chapterThreeStart=chapterThreeStart;window.showChapterThreePortraits=showChapterThreePortraits;window.chapterThreeClue=chapterThreeClue;window.chapterFour=chapterFour;

// Remove the Forms-only QR cards while retaining the actual clue graphics.
const chapterTwoBase=chapterTwo;
chapterTwo=function(){chapterTwoBase();document.querySelector('img[src$="asset-original-assets-chapter-2-2.jpg"]')?.closest('figure')?.remove()};
const chapterFourBase=chapterFour;
chapterFour=function(){chapterFourBase();document.querySelector('img[src$="asset-original-assets-chapter-4-2.jpg"]')?.closest('figure')?.remove()};

// The Chapter 3 source has separate image sets for the library, portraits, and the clue.
const chapterThreeStartBase=chapterThreeStart;
chapterThreeStart=function(){chapterThreeStartBase();const answer=document.querySelector('.answer');answer?.insertAdjacentHTML('beforebegin','<section class="gallery"><figure><img src="asset-chapter3-library.jpg" alt="Storrs Library"><figcaption>The Storrs Library</figcaption></figure></section>')};
const showChapterThreePortraitsBase=showChapterThreePortraits;
showChapterThreePortraits=function(){showChapterThreePortraitsBase();document.querySelectorAll('img[src*="original-assets/chapter-3/"]').forEach((img,i)=>{img.src=`asset-chapter3-portrait-${i+1}.jpg`})};
const chapterThreeClueBase=chapterThreeClue;
chapterThreeClue=function(){chapterThreeClueBase();const answer=document.querySelector('.answer');answer?.insertAdjacentHTML('beforebegin','<section class="gallery"><figure><img src="asset-chapter3-librarian.jpg" alt="The librarian"><figcaption>The librarian</figcaption></figure><figure><img src="asset-chapter3-clue-front.jpg" alt="Folded slip of paper, front"><figcaption>Folded slip of paper (front)</figcaption></figure><figure><img src="asset-chapter3-clue-back.jpg" alt="Folded slip of paper, back"><figcaption>Folded slip of paper (back)</figcaption></figure></section>')};
window.chapterTwo=chapterTwo;window.chapterFour=chapterFour;window.chapterThreeStart=chapterThreeStart;window.showChapterThreePortraits=showChapterThreePortraits;window.chapterThreeClue=chapterThreeClue;

// Keep the main Chapter 3 clue usable on a phone after moving between its screens.
const chapterThreeClueDisplay=chapterThreeClue;
chapterThreeClue=function(){chapterThreeClueDisplay();const answer=document.querySelector('.answer');answer?.insertAdjacentHTML('beforebegin','<button class="button ghost full" onclick="showChapterThreePortraits()">View the portraits</button>');requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"auto"}))};
window.chapterThreeClue=chapterThreeClue;

// Hints reveal progressively and remain available when players leave and return.
const revealedHints=JSON.parse(localStorage.getItem('staff-ministry-hints')||'{}');
const chapterHints={
  1:[
    '<strong>Hint #1: Focus on the Shapes.</strong><br>The clue has two main elements: floating stars and intercepting lines. They are not placed randomly. Look at how these shapes interact with the real world.',
    '<strong>Hint #2: Alignment is Key.</strong><br>Some stars align perfectly with circular orbs, while others float off-center. The lines indicate where branches cross. View the sculpture and clue from where the clue was found.',
    '<strong>Hint #3: Filtering Out The Noise.</strong><br>Look only at the letters attached to stars that perfectly line up with an orb.',
    '<strong>Hint #4: Where to Next?</strong><br>The correctly aligned stars spell a seven-letter word for the next physical destination. Read them left to right.',
    '<strong>Hint #5: The solved puzzle.</strong><br>Make your way to Storrs Library and see what you can find there.'
  ],
  2:[
    '<strong>Hint #1: Who is Who?</strong><br>Reverend Richard Salter Storrs (1763–1819) wears an older 18th-century black clerical robe with white collar tabs. Reverend Richard S. Storrs of Brooklyn (1821–1900) has prominent white mutton-chop sideburns. Mary Elwell (Jenks) Storrs is the elegant woman in the gold frame. Professor Richard S. Storrs wears a 19th-century suit and is in black and white.',
    '<strong>Hint #2: Use the clue left behind by the strange lady.</strong><br>After identifying each person, find that family member’s red letter on the Storrs family-tree clue and read the portraits from left to right.',
    '<strong>Hint #3: Put the letters in the correct order.</strong><br>The first portrait is Rev. Richard S. Storrs (1763–1819), whose associated letter is C. Continue across the portraits in order.'
  ],
  3:[
    '<strong>Hint #1: Where do I start?</strong><br>Find the true/false answers at red-star houses, street signs with the town seal, the Green behind the war memorials, the witness stones, and the memorial plaques.',
    '<strong>Hint #2: Some visual clues.</strong><br>Use the visual-reference clue to help identify the locations for the true/false statements.',
    '<strong>Hint #3: What are the T/F answers?</strong><br>1T, 2T, 3T, 4F, 5T, 6F, 7F, 8F, 9F.',
    '<strong>Hint #4: Now what?!</strong><br>Use the correct answers to connect the dots. Pay attention to the number and color pairs.',
    '<strong>Hint #5: How do I connect the dots?</strong><br>Start with the green dot marked 1 because statement 1 is true, then use the green dot marked 2, and continue through all nine dots.',
    '<strong>Hint #6: The solved puzzle.</strong><br>The connected dots reveal the house number on Williams Street.'
  ]
};
function hintPanel(chapter){const count=revealedHints[chapter]||0;const hints=chapterHints[chapter];const shown=hints.slice(0,count).map(text=>`<p>${text}</p>`).join('');const control=count<hints.length?`<button class="button ghost full" onclick="revealNextHint(${chapter})">${count?'Show another hint':'I need a hint'}</button>`:'<p class="small"><strong>No more hints available</strong></p>';return `<section class="hint-progress">${shown}${control}</section>`}
function revealNextHint(chapter){revealedHints[chapter]=Math.min((revealedHints[chapter]||0)+1,chapterHints[chapter].length);localStorage.setItem('staff-ministry-hints',JSON.stringify(revealedHints));if(chapter===1)chapterTwo();else if(chapter===2)chapterThreeClue();else if(chapter===3)chapterFour();else window.chapter(chapter);requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'auto'})))}

const chapterTwoHintsDisplay=chapterTwo;
chapterTwo=function(){chapterTwoHintsDisplay();const old=document.querySelector('.answer details.hint');if(old)old.outerHTML=hintPanel(1)};

const chapterThreeHintsDisplay=chapterThreeClue;
chapterThreeClue=function(){chapterThreeHintsDisplay();const old=document.querySelector('.answer details.hint');if(old)old.outerHTML=hintPanel(2);window.scrollTo({top:0,behavior:'auto'})};
const chapterFourHintsDisplay=chapterFour;
chapterFour=function(){chapterFourHintsDisplay();document.querySelectorAll('img[src$="asset-original-assets-chapter-4-1.jpg"],img[src$="asset-original-assets-chapter-4-7.jpg"],img[src$="asset-original-assets-chapter-4-8.jpg"],img[src$="asset-original-assets-chapter-4-9.jpg"],img[src$="asset-original-assets-chapter-4-10.jpg"]').forEach(img=>img.closest('figure')?.remove());const old=document.querySelector('.answer details.hint');if(old)old.outerHTML=hintPanel(3);window.scrollTo({top:0,behavior:'auto'})};
const imageLabels={
  'c1-1.jpg':'Mr. Potato Head', 'c1-2.jpg':'The cryptic note (front)', 'c1-3.jpg':'The cryptic note (back)',
  'asset-original-assets-chapter-2-1.jpg':'Map to the Harold Grinspoon “Life” Sculpture', 'asset-original-assets-chapter-2-3.jpg':'Harold Grinspoon (born in 1929)', 'asset-original-assets-chapter-2-4.jpg':'The clue left in front of the sculpture', 'asset-original-assets-chapter-2-5.jpg':'The view from where the clue was left', 'asset-original-assets-chapter-2-6.jpg':'The view from where the clue was left', 'asset-original-assets-chapter-2-7.jpg':'The clue and the sculpture', 'asset-original-assets-chapter-2-8.jpg':'Map to Storrs Library',
  'asset-original-assets-chapter-4-1.jpg':'Map to First Church of Christ', 'asset-original-assets-chapter-4-3.jpg':'The panicked groom', 'asset-original-assets-chapter-4-4.jpg':'First Church of Christ', 'asset-original-assets-chapter-4-5.jpg':'Enigmatic paper #1', 'asset-original-assets-chapter-4-6.jpg':'Enigmatic paper #2', 'asset-original-assets-chapter-4-7.jpg':'Some visual clues', 'asset-original-assets-chapter-4-8.jpg':'Map to 20 Williams Street', 'asset-original-assets-chapter-4-9.jpg':'The solved puzzle', 'asset-original-assets-chapter-4-10.jpg':'20 Williams Street'
};
function applyImageLabels(){document.querySelectorAll('.gallery figure').forEach(figure=>{const image=figure.querySelector('img');const caption=figure.querySelector('figcaption');if(!image||!caption)return;const key=Object.keys(imageLabels).find(k=>image.getAttribute('src')?.endsWith(k));if(key)caption.textContent=imageLabels[key]})}
const chapterTwoLabels=chapterTwo;chapterTwo=function(){chapterTwoLabels();applyImageLabels()};
const chapterThreeStartLabels=chapterThreeStart;chapterThreeStart=function(){chapterThreeStartLabels();applyImageLabels()};
const showChapterThreePortraitsLabels=showChapterThreePortraits;showChapterThreePortraits=function(){showChapterThreePortraitsLabels();applyImageLabels()};
const chapterThreeClueLabels=chapterThreeClue;chapterThreeClue=function(){chapterThreeClueLabels();applyImageLabels()};
const chapterFourLabels=chapterFour;chapterFour=function(){chapterFourLabels();applyImageLabels()};
window.chapterTwo=chapterTwo;window.chapterThreeStart=chapterThreeStart;window.showChapterThreePortraits=showChapterThreePortraits;window.chapterThreeClue=chapterThreeClue;window.chapterFour=chapterFour;window.revealNextHint=revealNextHint;
const chapterWithLabels=chapter;chapter=function(n){chapterWithLabels(n);applyImageLabels()};window.chapter=chapter;

// The remaining chapters use the same progressive hint treatment during the rebuild.
chapterHints[4]=[
  '<strong>Hint #1: Where do I need to look?</strong><br>Look up at the scroll pediment above the main door. Match the symbols there to the pictures on the clue left in the bench frame.',
  '<strong>Hint #2: Making sense of it all.</strong><br>Use the real-world clue to place the symbols, and their letters, in order from left to right.',
  '<strong>Hint #3: A common palindrome.</strong><br>The stonework runs pineapple, scroll, rosette, central flame, then mirrors back through rosette, scroll, and pineapple.',
  '<strong>Hint #4: Solved puzzle.</strong><br>The ordered letters reveal a common palindrome.'
];
chapterHints[5]=['<strong>Hint #1.</strong><br>Use the lines on the memorial and the line positions on the clue together.','<strong>Hint #2.</strong><br>There are exactly nine lines of text on the memorial and nine positions on the clue.'];
chapterHints[6]=['<strong>Hint #1.</strong><br>Notice the colors and patterns on the note, then look around and higher up for matching details.','<strong>Hint #2.</strong><br>Think about the “Ding-Ding!” sound and the historical vehicle that made it.','<strong>Hint #3.</strong><br>Before cars, electric streetcars ran down Route 5. What is another four-letter word for a trolley?'];
chapterHints[7]=['<strong>Hint #1: Look around.</strong><br>Identify the store or business names associated with the features in the Polaroids.','<strong>Hint #2: Focus on the letters.</strong><br>Each Polaroid tells you which letter to take from its store name.','<strong>Hint #3: An example.</strong><br>The CHICO lights have the number 3, so take the third letter: I.','<strong>Hint #4: The Polaroid answers.</strong><br>CHICO, Urgent Care, McKenna & Caban, CVS, Warby Parker, Fleet Feet, Delaney, and Max Burger spell the final answer.'];
const chapterWithProgressiveHints=chapter;chapter=function(n){chapterWithProgressiveHints(n);if(n>=4){const old=document.querySelector('.answer details.hint');if(old)old.outerHTML=hintPanel(n)}};window.chapter=chapter;

function chapterFive(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 5 of 8</span></div><article class="card chapter original"><p class="location">📍 20 Williams Street</p><p>Good job completing Chapter 4 and welcome to Chapter 5!</p><h3>The Second Town Hall</h3><p>You arrive at 20 Williams Street, a Colonial Revival building that served as Longmeadow’s Town Hall before the move to Greenwood Center. The town’s civic hubs have a habit of shifting: early meetings took place on the Green in 1716, the first municipal office opened at 417 Longmeadow Street in 1905, the town moved here in 1930, and it moved again to Greenwood Center in late 2024.</p><p>The thief is nowhere to be found. As you sit on the bench, you notice a slip of paper wedged into its frame. A new puzzle awaits.</p><section class="gallery"><figure><img src="asset-original-assets-chapter-5-1.jpg" alt="Map to 20 Williams Street"><figcaption>Map to 20 Williams Street</figcaption></figure><figure><img src="asset-original-assets-chapter-5-4.jpg" alt="20 Williams Street"><figcaption>20 Williams Street</figcaption></figure><figure><img src="asset-original-assets-chapter-5-3.jpg" alt="The clue left by the thief"><figcaption>The clue left by the thief</figcaption></figure><figure><img src="asset-original-assets-chapter-5-6.jpg" alt="The scroll pediment"><figcaption>The scroll pediment at 20 Williams Street</figcaption></figure></section><section class="answer"><h3>Did you solve the puzzle?</h3><button class="button full" onclick="submitAnswer(4)">Yes — submit our answer</button>${hintPanel(4)}</section></article>`) }
function chapterFiveRacecar(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="chapter(4)">← Back to Chapter 5</button><span class="small">Chapter 5 of 8</span></div><article class="card chapter original"><h3>Racecar?! Race car?! What in the world could that mean?</h3><p>A deafening roar echoes from behind the police station. A sleek race car, its driver hidden behind pitch-black tinted windows, tears down Williams Street toward the center of town. A hand flashes out of the window and tosses a handwritten note onto the pavement.</p><section class="gallery"><figure><img src="asset-original-assets-chapter-5-9.jpg" alt="The clue left by the thief"><figcaption>The clue left by the thief</figcaption></figure><figure><img src="asset-original-assets-chapter-5-10.jpg" alt="Map to Ann Scibelli’s memorial"><figcaption>Map to Ann Scibelli’s memorial</figcaption></figure><figure><img src="asset-original-assets-chapter-5-11.jpg" alt="Ann Scibelli’s memorial"><figcaption>Ann Scibelli’s memorial</figcaption></figure><figure><img src="asset-original-assets-chapter-5-12.jpg" alt="The stone"><figcaption>The stone</figcaption></figure></section><section class="answer"><h3>Did you find the location of your next test?</h3><button class="button full" onclick="completeChapter(4)">Yes — continue</button><section class="hint-progress"><p><strong>Hint:</strong> The place you are looking for is Ann Scibelli’s memorial, near 134 Williams Street on the median between Williams Street and Parkside Drive.</p></section></section></article>`) }
const chapterWithFive=chapter;chapter=function(n){if(n===4)return chapterFive();chapterWithFive(n)};window.chapter=chapter;window.chapterFive=chapterFive;window.chapterFiveRacecar=chapterFiveRacecar;

Object.assign(imageLabels,{
  'c5-1.jpg':'The clue left by the thief',
  'c6-1.jpg':'The clue left at Ann Scibelli’s memorial', 'c6-2.jpg':'The memorial clue',
  'c7-1.jpg':'The Ding-Ding clue', 'c7-2.jpg':'The Longmeadow trolley',
  'c8-1.jpg':'The photographer', 'c8-2.jpg':'The stack of Polaroids'
});

function chapterFiveSecondPuzzle(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="chapter(4)">← Back to Chapter 5</button><span class="small">Chapter 5 of 8</span></div><article class="card chapter original"><h3>Racecar?! Race car?! What in the world could that mean?</h3><p>As you stand there scratching your head, a sudden, deafening roar echoes from behind the police station.</p><p>In a flash, a sleek race car screeches into view, its driver completely hidden behind pitch-black tinted windows. It zooms right past you, tears a sharp left onto Williams Street, and barrels toward the center of town. There is no way this is a coincidence—the clue you just decoded is unfolding right before your eyes.</p><p>You sprint after it. While catching up to a speeding car is impossible, you spot a hand flash out of the driver window and toss something onto the pavement. Following the tire tracks down Williams Street, you find a crisp handwritten note sitting on the sidewalk. You reach down and pick it up: your next clue.</p><section class="gallery"><figure><img src="asset-original-assets-chapter-5-9.jpg" alt="The clue left by the thief"><figcaption>The clue left by the thief</figcaption></figure></section><section class="answer"><h3>Do you know your next destination?</h3><button class="button full" onclick="submitChapterFiveSecondAnswer()">Yes — submit our answer</button><button class="button ghost full" onclick="showChapterFiveSecondHint()">No — I need a hint</button></section></article>`) }
function showChapterFiveSecondHint(){chapterFiveSecondPuzzle();const answer=document.querySelector('.answer');answer?.insertAdjacentHTML('beforeend','<section class="hint-progress"><p><strong>Hint:</strong> The place you are looking for is Ann Scibelli’s memorial, near 134 Williams Street on the median between Williams Street and Parkside Drive.</p><section class="gallery"><figure><img src="asset-original-assets-chapter-5-10.jpg" alt="Map to Ann Scibelli’s memorial"><figcaption>Map to Ann Scibelli’s memorial</figcaption></figure><figure><img src="asset-original-assets-chapter-5-11.jpg" alt="Ann Scibelli’s memorial"><figcaption>Ann Scibelli’s memorial</figcaption></figure><figure><img src="asset-original-assets-chapter-5-12.jpg" alt="The stone"><figcaption>The stone</figcaption></figure></section><p class="small"><strong>No more hints available</strong></p></section>');requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'auto'}))}
function submitChapterFiveSecondAnswer(){app.innerHTML=wrap(`<section class="card answer"><p class="eyebrow">Submit your answer</p><h2>What is your next destination?</h2><input id="solution" class="solution" autocomplete="off" placeholder="Your answer"><button class="button full" onclick="checkChapterFiveSecondAnswer()">Submit answer</button><p id="feedback" class="small"></p><button class="button ghost" onclick="chapterFiveSecondPuzzle()">← Back to puzzle</button></section>`)}
function checkChapterFiveSecondAnswer(){const entered=document.querySelector('#solution').value.toLowerCase().replace(/[^a-z0-9]/g,'');if(entered.includes('shops'))completeChapter(4);else document.querySelector('#feedback').textContent='Incorrect. Review the clue and hint, then try again.'}
chapterFiveRacecar=chapterFiveSecondPuzzle;window.chapterFiveRacecar=chapterFiveRacecar;window.chapterFiveSecondPuzzle=chapterFiveSecondPuzzle;window.showChapterFiveSecondHint=showChapterFiveSecondHint;window.submitChapterFiveSecondAnswer=submitChapterFiveSecondAnswer;window.checkChapterFiveSecondAnswer=checkChapterFiveSecondAnswer;

function chapterFiveSecondPuzzleUpdated(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="chapter(4)">← Back to Chapter 5</button><span class="small">Chapter 5 of 8</span></div><article class="card chapter original"><h3>Racecar?! Race car?! What in the world could that mean?</h3><p>As you stand there scratching your head, a sudden, deafening roar echoes from behind the police station.</p><p>In a flash, a sleek race car screeches into view, its driver completely hidden behind pitch-black tinted windows. It zooms right past you, tears a sharp left onto Williams Street, and barrels toward the center of town. There is no way this is a coincidence—the clue you just decoded is unfolding right before your eyes.</p><p>You sprint after it. While catching up to a speeding car is impossible, you spot a hand flash out of the driver window and toss something onto the pavement. Following the tire tracks down Williams Street, you find a crisp handwritten note sitting on the sidewalk. You reach down and pick it up: your next clue.</p><section class="gallery"><figure><img src="asset-original-assets-chapter-5-9.jpg" alt="The clue left by the thief"><figcaption>The clue left by the thief</figcaption></figure></section><section class="answer"><h3>Did you find the location that the thief hinted at?</h3><button class="button full" onclick="completeChapter(4)">Yes</button><button class="button ghost full" onclick="showChapterFiveSecondHint()">No — I need a hint</button></section></article>`) }
chapterFiveSecondPuzzle=chapterFiveSecondPuzzleUpdated;chapterFiveRacecar=chapterFiveSecondPuzzleUpdated;window.chapterFiveSecondPuzzle=chapterFiveSecondPuzzle;window.chapterFiveRacecar=chapterFiveRacecar;

function chapterSix(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 6 of 8</span></div><article class="card chapter original"><p class="location">📍 Ann Scibelli’s Memorial</p><p>Good job completing Chapter 5 and welcome to Chapter 6!</p><h3>A Place to Rest, Reflect and Renew</h3><p>You are standing in front of Ann Scibelli’s memorial stone. A colorful piece of paper is wedged between two pavers. Study the pattern and put the pieces together.</p><section class="gallery"><figure><img src="asset-original-assets-chapter-6-1.jpg" alt="Map to Ann Scibelli’s Memorial"><figcaption>Map to Ann Scibelli’s Memorial</figcaption></figure><figure><img src="asset-original-assets-chapter-6-2.jpg" alt="Ann Scibelli’s Memorial"><figcaption>Ann Scibelli’s Memorial</figcaption></figure><figure><img src="c6-1.jpg" alt="The clue left by the thief"><figcaption>The clue left by the thief</figcaption></figure><figure><img src="c6-2.jpg" alt="The 5-letter code clue"><figcaption>The 5-letter code clue</figcaption></figure></section><section class="answer"><h3>Did you crack the code and know where to go next?</h3><button class="button full" onclick="submitAnswer(5)">Yes — submit our answer</button>${hintPanel(5)}</section></article>`) }
function chapterSeven(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 7 of 8</span></div><article class="card chapter original"><p class="location">📍 Razzmatazz</p><p>Good job completing Chapter 6 and welcome to Chapter 7!</p><h3>The Ding-Ding clue!</h3><p>You arrive at Razzmatazz, where an employee holds a mysterious slip of paper. An eccentric woman tossed it high in the air and shouted <strong>“Ding-Ding!”</strong> before disappearing. Can you crack the mystery?</p><section class="gallery"><figure><img src="c7-1.jpg" alt="The Ding-Ding clue"><figcaption>The Ding-Ding clue</figcaption></figure><figure><img src="c7-2.jpg" alt="The Longmeadow trolley"><figcaption>The Longmeadow trolley</figcaption></figure></section><section class="answer"><h3>Did you find the 4-letter word hidden behind the clue?</h3><button class="button full" onclick="submitAnswer(6)">Yes — submit our answer</button>${hintPanel(6)}</section></article>`) }
const chapterWithSixSeven=chapter;chapter=function(n){if(n===5)return chapterSix();if(n===6)return chapterSeven();chapterWithSixSeven(n)};window.chapter=chapter;window.chapterSix=chapterSix;window.chapterSeven=chapterSeven;

function chapterEight(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 8 of 8</span></div><article class="card chapter original"><p class="location">📍 The Longmeadow Shops, north of Bliss Road</p><p>Good job completing Chapter 7 and welcome to the final Chapter 8!</p><h3>The Strange Photographer</h3><p>You arrive at the Longmeadow Shops and spot a lady taking photographs with an old-fashioned Polaroid camera.</p><p>“You can read a town’s history like an open book just by looking at its storefronts!” she says. “The shop names hold a hidden message—one letter at a time. Put the right pieces together, and you’ll find the coolest reward in town.”</p><p>She hands you a stack of pictures. This is your final test: solve the puzzle to retrieve the Staff of Ministry and save Longmeadow from reverting to wilderness.</p><section class="gallery"><figure><img src="c8-1.jpg" alt="The photographer"><figcaption>The photographer</figcaption></figure><figure><img src="c8-2.jpg" alt="The stack of Polaroids"><figcaption>The stack of Polaroids</figcaption></figure></section><section class="answer"><h3>Did you decode your last clue?</h3><button class="button full" onclick="submitAnswer(7)">Yes — submit our answer</button>${hintPanel(7)}</section></article>`) }
const chapterWithEight=chapter;chapter=function(n){if(n===7)return chapterEight();chapterWithEight(n)};window.chapter=chapter;window.chapterEight=chapterEight;

// Chapter 6: retain the complete original introduction and reveal every hint one at a time.
chapterHints[5]=[
  '<strong>Hint #1: Lines</strong><br>Ummm...Could this be a coincidence?! There are exactly 9 lines of text etched into the memorial stone and 9 line positions* mentioned on the clue left by the thief.<br><br><em>*Look closely on the left side of the clue for the “line position” label.</em>',
  '<strong>Hint #2: Words</strong><br>At the top of the matrix, you notice details about word positions. It stands to reason that cross-referencing a line number with a word position yields a specific word from the stone.<br><br>For instance, the yellow square is positioned at Line 1, Word 2. The second word on the first line of the tribute stone is <strong>PLACE</strong>.',
  '<strong>Hint #3: Letters</strong><br>You should now have five words in front of you, but the puzzle isn’t finished yet. Look back at the matrix: the number tucked inside each colored square tells you exactly which letter to extract from its corresponding word.<br><br>For example, the yellow square has the number 1 in it. That means the letter to extract from the word <strong>PLACE</strong> is <strong>P</strong> (the first letter).',
  '<strong>Hint #4: Colors</strong><br>Now you have your five letters, but how do you arrange them to reveal the final word? You might be sharp enough to unscramble it on your own—but if you want to be absolutely sure, look closely at the sequence of colors for the 5-letter code at the bottom of the clue: <strong>PINK, SALMON, GREEN, YELLOW, BLUE.</strong> Let the colors guide your path!'
];

chapterSix=function(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 6 of 8</span></div><article class="card chapter original"><p class="location">📍 Ann Scibelli’s Memorial</p><p>Good job completing Chapter 5 and welcome to Chapter 6!</p><h3>A Place to Rest, Reflect and Renew</h3><p>You are now standing in front of Ann Scibelli's memorial stone. Ann was a beloved member of the Longmeadow community. Looking around, you notice a small, <strong>colorful piece of paper</strong> wedged neatly between two pavers. You carefully pull it free and examine it. What could that mean? You pull out your notebook, study the pattern, and start putting the pieces together...</p><section class="gallery"><figure><img src="asset-original-assets-chapter-6-1.jpg" alt="Map to Ann Scibelli’s Memorial"><figcaption>Map to Ann Scibelli’s Memorial</figcaption></figure><figure><img src="asset-original-assets-chapter-6-2.jpg" alt="Ann Scibelli’s Memorial"><figcaption>Ann Scibelli’s Memorial</figcaption></figure><figure><img src="c6-1.jpg" alt="Piece of paper found between two pavers, front"><figcaption>Piece of paper found between two pavers (front)</figcaption></figure><figure><img src="c6-2.jpg" alt="Piece of paper found between two pavers, back"><figcaption>Piece of paper found between two pavers (back)</figcaption></figure></section><section class="answer"><h3>Did you crack the code and know where to go next?</h3><button class="button full" onclick="submitAnswer(5)">Yes — submit our answer</button>${hintPanel(5)}</section></article>`) };
window.chapterSix=chapterSix;

// The start screen reflects saved progress and provides a deliberate, reversible-in-intent reset flow.
function home(){const hasProgress=S.u>0||S.d.length>0;app.innerHTML=wrap(`<section class="card original"><h2>Get ready for a <strong>FREE, interactive, historical mystery adventure through Longmeadow!</strong></h2><p>Welcome! We are a local Longmeadow family who loves puzzles, outdoor adventures, and our town’s rich history! We built this interactive mystery trail so neighbors, friends, and families could explore Longmeadow in a fun, new way together.</p><p><strong>How to play:</strong> Start at Bliss Park Playground, follow clues from destination to destination, use hints when needed, and bring a charged phone plus pencil and paper.</p><p>🚲 Consider bikes or scooters: the adventure spans 8 destinations across a 4-mile trail. Travel safely, respect private property, and play at your own pace.</p><button class="button full" onclick="map()">${hasProgress?'Continue the adventure':'Begin the adventure'}</button><button class="button ghost full restart-adventure" onclick="restartAdventurePrompt()">Restart the adventure</button></section>`)}
function restartAdventurePrompt(){app.innerHTML=wrap(`<section class="card answer"><p class="eyebrow">Restart the adventure</p><h2>Reset all progress?</h2><p>This will reset your unlocked chapters and every hint you have revealed. This cannot be undone.</p><button class="button full" onclick="confirmRestartAdventure()">Yes — reset my adventure</button><button class="button ghost full" onclick="home()">No — keep my progress</button></section>`)}
function confirmRestartAdventure(){S.u=0;S.d=[];Object.keys(revealedHints).forEach(key=>delete revealedHints[key]);localStorage.setItem('staff-ministry-progress',JSON.stringify(S));localStorage.setItem('staff-ministry-hints',JSON.stringify(revealedHints));home()}
window.home=home;window.restartAdventurePrompt=restartAdventurePrompt;window.confirmRestartAdventure=confirmRestartAdventure;
home();

// All completed hint sequences offer the answer only when the player deliberately asks for it.
const revealedSolutions=JSON.parse(localStorage.getItem('staff-ministry-solutions')||'{}');
const chapterSolutions={0:'76',1:'LIBRARY',2:'CHURCH',3:'20',4:'RACECAR',5:'SHOPS',6:'TRAM',7:'ICE CREAM'};
hintPanel=function(chapter){const count=revealedHints[chapter]||0;const hints=chapterHints[chapter]||[];const shown=hints.slice(0,count).map(text=>`<p>${text}</p>`).join('');let control='';if(count<hints.length)control=`<button class="button ghost full" onclick="revealNextHint(${chapter})">${count?'Show another hint':'I need a hint'}</button>`;else if(revealedSolutions[chapter])control=`<p class="solution-reveal"><strong>Solution: ${chapterSolutions[chapter]}</strong></p>`;else control=`<button class="button ghost full" onclick="revealSolution(${chapter})">Just show me the solution!</button>`;return `<section class="hint-progress">${shown}${control}</section>`};
function revealSolution(chapter){revealedSolutions[chapter]=true;localStorage.setItem('staff-ministry-solutions',JSON.stringify(revealedSolutions));if(chapter===1)chapterTwo();else if(chapter===2)chapterThreeClue();else if(chapter===3)chapterFour();else window.chapter(chapter);requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'auto'})))}
window.revealSolution=revealSolution;

// Restore the full historical introduction to Chapter 5.
chapterFive=function(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 5 of 8</span></div><article class="card chapter original"><p class="location">📍 20 Williams Street</p><p>Good job completing Chapter 4 and welcome to Chapter 5!</p><h3>The Second Town Hall</h3><p>You arrive at 20 Williams Street, a beautiful Colonial Revival building that served as Longmeadow's Town Hall before the recent move to Greenwood Center. The town's civic hubs have a habit of shifting over time:</p><p><strong>1716:</strong> Early town meetings take place at the multi-purpose Meeting House right on the Town Green.</p><p><strong>1905:</strong> The town opens its first official municipal office at 417 Longmeadow St, retrofitting an 1873 one-room schoolhouse with a secure record vault.</p><p><strong>1930:</strong> The town moves here to 20 Williams St, building a spacious new hub that remains a centerpiece of the historic district.</p><p><strong>Late 2024:</strong> The town hall moves once again to the Greenwood Center at 231 Maple Road.</p><p>It looks like the town hall isn't the only thing that relocated — the thief is nowhere to be found! Dejected, you sit down on the bench in front of the building. As you lean back, you notice a slip of paper wedged into the bench frame. You pull it out. A new puzzle awaits...</p><section class="gallery"><figure><img src="asset-original-assets-chapter-5-1.jpg" alt="Map to 20 Williams Street"><figcaption>Map to 20 Williams Street</figcaption></figure><figure><img src="asset-original-assets-chapter-5-4.jpg" alt="20 Williams Street"><figcaption>20 Williams Street</figcaption></figure><figure><img src="asset-original-assets-chapter-5-3.jpg" alt="Slip of paper wedged into the bench frame"><figcaption>Slip of paper wedged into the bench frame</figcaption></figure><figure><img src="asset-original-assets-chapter-5-6.jpg" alt="The scroll pediment at 20 Williams Street"><figcaption>The scroll pediment at 20 Williams Street</figcaption></figure></section><section class="answer"><h3>Did you solve the puzzle?</h3><button class="button full" onclick="submitAnswer(4)">Yes — submit our answer</button>${hintPanel(4)}</section></article>`) };
window.chapterFive=chapterFive;

// Chapters 7 and 8 now use the original narrative, puzzle resources, and exact hint text.
chapterHints[6]=[
  '<strong>Hint #1</strong><br>Notice the colors and patterns on the note? Look around—and higher up! Can you spot where those same design details appear in the real world?',
  '<strong>Hint #2</strong><br>Study the visual clue again and compare it with the details around Razzmatazz.',
  '<strong>Hint #3</strong><br>Think about the mysterious “Ding-Ding!” sound made by the stranger outside Razzmatazz. What kind of historical vehicle made that famous ringing sound as it rolled down the street?',
  '<strong>Hint #4</strong><br>Before cars filled the roads in the early 1900s, electric streetcars ran up and down Route 5 through Longmeadow. What is another 4-letter word for a trolley?'
];
chapterHints[7]=[
  '<strong>Hint #1: Look around</strong><br>Look at the Polaroid images. Can you figure out the stores/business names associated with those features at the Longmeadow Shops?',
  '<strong>Hint #2: Focus on the letters of the store/business names</strong><br>Once you have found the names that match each feature on the Polaroids, you need to choose one letter from each store/business name. Look for something else on the Polaroids that might tell you which letter to choose.',
  '<strong>Hint #3: An example</strong><br>The first Polaroid shows the lights on top of the CHICO store logo, and it has the number 3. Take the 3rd letter from the store name, an <strong>I</strong>. Try these with the other Polaroids to spell your answer!',
  '<strong>Hint #4: The Polaroid answers</strong><br>Polaroid #1: CHICO (3rd letter: I)<br>Polaroid #2: Urgent Care (7th letter: C)<br>Polaroid #3: McKenna &amp; Caban (4th letter: E)<br>Polaroid #4: CVS (1st letter: C)<br>Polaroid #5: Warby Parker (3rd letter: R)<br>Polaroid #6: Fleet Feet (3rd letter: E)<br>Polaroid #7: Delaney (4th letter: A)<br>Polaroid #8: Max Burger (1st letter: M)'
];
chapterSeven=function(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 7 of 8</span></div><article class="card chapter original"><p class="location">📍 Razzmatazz Kids toy store — 803 Williams St, Longmeadow, MA 01106</p><p>Good job completing Chapter 6 and welcome to Chapter 7!</p><h3>The Ding-Ding clue!</h3><p>You arrive at Razzmatazz, where an employee is waiting outside, holding a mysterious slip of paper. She tells you that moments ago, an eccentric woman marched past the store, tossed the note high into the air, and shouted <strong>“Ding-Ding!”</strong> at the top of her lungs before disappearing. The employee has no idea what the wild proclamation means. Can you crack the mystery?</p><section class="gallery"><figure><img src="asset-original-assets-chapter-7-4.jpg" alt="The toy store employee"><figcaption>The toy store employee</figcaption></figure><figure><img src="asset-original-assets-chapter-7-5.jpg" alt="The Ding-Ding clue"><figcaption>The Ding-Ding clue</figcaption></figure></section><section class="answer"><h3>Did you find the 4-letter word hidden behind the clue?</h3><button class="button full" onclick="submitAnswer(6)">Yes — submit our answer</button>${hintPanel(6)}</section></article>`) };
chapterEight=function(){app.innerHTML=wrap(`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter 8 of 8</span></div><article class="card chapter original"><p class="location">📍 The Longmeadow Shops — north side of Bliss Road</p><p>Good job completing Chapter 7 and welcome to the final Chapter 8!</p><h3>The Strange Photographer</h3><p>You arrive at the Longmeadow Shops and waste no time searching for the photographer. Sure enough, you spot a lady snapping photos with an old-fashioned Polaroid camera.</p><p>“You can read a town's history like an open book just by looking at its storefronts!” she says with a knowing smile. “The shop names hold a hidden message—one letter at a time. Put the right pieces together, and you'll find the coolest reward in town. Want to look at my pictures?”</p><p>Before you even have a chance to answer, she hands you a stack of pictures and turns right back to taking photos. You examine the prints closely. This is your final test. Solve the puzzle to retrieve the Staff of Ministry and save Longmeadow from reverting to wilderness! No time to waste!</p><section class="gallery"><figure><img src="asset-original-assets-chapter-8-4.jpg" alt="The photographer"><figcaption>The photographer</figcaption></figure><figure><img src="asset-original-assets-chapter-8-5.jpg" alt="The stack of Polaroids"><figcaption>The stack of Polaroids</figcaption></figure></section><section class="answer"><h3>Did you decode your last clue?</h3><button class="button full" onclick="submitAnswer(7)">Yes — submit our answer</button>${hintPanel(7)}</section></article>`) };
const chapterWithRestoredLateChapters=chapter;chapter=function(n){if(n===4)return chapterFive();if(n===5)return chapterSix();if(n===6)return chapterSeven();if(n===7)return chapterEight();chapterWithRestoredLateChapters(n)};window.chapter=chapter;window.chapterSeven=chapterSeven;window.chapterEight=chapterEight;

function showChapterFiveSecondHint(){chapterFiveSecondPuzzle();const answer=document.querySelector('.answer');answer?.insertAdjacentHTML('beforeend','<section class="hint-progress"><p><strong>Hint:</strong> The place you are looking for is Ann Scibelli’s memorial, near 134 Williams Street on the median between Williams Street and Parkside Drive.</p><section class="gallery"><figure><img src="asset-original-assets-chapter-5-10.jpg" alt="Map to Ann Scibelli’s memorial"><figcaption>Map to Ann Scibelli’s memorial</figcaption></figure><figure><img src="asset-original-assets-chapter-5-11.jpg" alt="Ann Scibelli’s memorial"><figcaption>Ann Scibelli’s memorial</figcaption></figure><figure><img src="asset-original-assets-chapter-5-12.jpg" alt="The stone"><figcaption>The stone</figcaption></figure></section><button class="button ghost full" onclick="showChapterFiveSecondSolution()">Just show me the solution!</button></section>');requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'auto'}))}
function showChapterFiveSecondSolution(){showChapterFiveSecondHint();document.querySelector('.hint-progress')?.insertAdjacentHTML('beforeend','<p class="solution-reveal"><strong>Solution: Ann Scibelli’s memorial</strong></p>');document.querySelector('.hint-progress .button')?.remove()}
window.showChapterFiveSecondHint=showChapterFiveSecondHint;window.showChapterFiveSecondSolution=showChapterFiveSecondSolution;

function home(){const hasProgress=S.u>0||S.d.length>0;app.innerHTML=wrap(`<section class="card original"><h2>Get ready for a <strong>FREE, interactive, historical mystery adventure through Longmeadow!</strong></h2><p>Welcome! We are a local Longmeadow family who loves puzzles, outdoor adventures, and our town’s rich history! We built this interactive mystery trail so neighbors, friends, and families could explore Longmeadow in a fun, new way together.</p><p><strong>How to play:</strong> Start at Bliss Park Playground, follow clues from destination to destination, use hints when needed, and bring a charged phone plus pencil and paper.</p><p>🚲 Consider bikes or scooters: the adventure spans 8 destinations across a 4-mile trail. Travel safely, respect private property, and play at your own pace.</p><button class="button full" onclick="map()">${hasProgress?'Continue the adventure':'Begin the adventure'}</button><button class="button ghost full restart-adventure" onclick="restartAdventurePrompt()">Restart from the beginning</button></section>`)}
window.home=home;home();

// Chapter 1 also uses the progressive hint/solution treatment.
chapterHints[0]=['<strong>Hint #1</strong><br>Take a close look at the back of the cryptic note. The message points straight to your first destination!'];
const chapterWithEverySolution=chapter;chapter=function(n){chapterWithEverySolution(n);if(n===0){const old=document.querySelector('.answer details.hint');if(old)old.outerHTML=hintPanel(0)}};window.chapter=chapter;

// Images that explain a hint appear with that hint as it is revealed.
const hintImages={
  0:{0:[['c1-3.jpg','The cryptic note (back)']]},
  1:{0:[['asset-original-assets-chapter-2-4.jpg','The clue left in front of the sculpture'],['asset-original-assets-chapter-2-5.jpg','The view from where the clue was left']],1:[['asset-original-assets-chapter-2-7.jpg','The clue and the sculpture']],4:[['asset-original-assets-chapter-2-8.jpg','Map to Storrs Library']]},
  2:{0:[['asset-chapter3-clue-front.jpg','Folded slip of paper (front)'],['asset-chapter3-clue-back.jpg','Folded slip of paper (back)']]},
  3:{0:[['asset-original-assets-chapter-4-5.jpg','Enigmatic paper #1'],['asset-original-assets-chapter-4-6.jpg','Enigmatic paper #2']],1:[['asset-original-assets-chapter-4-7.jpg','Some visual clues']]},
  4:{0:[['asset-original-assets-chapter-5-6.jpg','The scroll pediment at 20 Williams Street'],['asset-original-assets-chapter-5-3.jpg','Slip of paper wedged into the bench frame']]},
  5:{0:[['c6-1.jpg','Piece of paper found between two pavers (front)'],['c6-2.jpg','Piece of paper found between two pavers (back)']]},
  6:{0:[['asset-original-assets-chapter-7-5.jpg','The Ding-Ding clue'],['asset-original-assets-chapter-7-6.jpg','Razzmatazz Kids store front']],2:[['asset-original-assets-chapter-7-7.jpg','The Longmeadow trolley']]},
  7:{0:[['asset-original-assets-chapter-8-5.jpg','The stack of Polaroids']]}
};
function hintImageGallery(chapter,index){const images=hintImages[chapter]?.[index]||[];if(!images.length)return '';return `<section class="gallery hint-images">${images.map(([src,label])=>`<figure><img src="${src}" alt="${label}"><figcaption>${label}</figcaption></figure>`).join('')}</section>`}
hintPanel=function(chapter){const count=revealedHints[chapter]||0;const hints=chapterHints[chapter]||[];const shown=hints.slice(0,count).map((text,index)=>`<p>${text}</p>${hintImageGallery(chapter,index)}`).join('');let control='';if(count<hints.length)control=`<button class="button ghost full" onclick="revealNextHint(${chapter})">${count?'Show another hint':'I need a hint'}</button>`;else if(revealedSolutions[chapter])control=`<p class="solution-reveal"><strong>Solution: ${chapterSolutions[chapter]}</strong></p>`;else control=`<button class="button ghost full" onclick="revealSolution(${chapter})">Just show me the solution!</button>`;return `<section class="hint-progress">${shown}${control}</section>`};

// Chapter 4's source page removes its spoiler image from the main clue page; restore it only after Hint #2 is revealed.
const chapterFourWithHintImageFix=chapterFour;
chapterFour=function(){chapterFourWithHintImageFix();if((revealedHints[3]||0)>=2&&!document.querySelector('.chapter-four-hint-two-image')){const secondHint=document.querySelector('.hint-progress > p:nth-of-type(2)');secondHint?.insertAdjacentHTML('afterend','<section class="gallery hint-images chapter-four-hint-two-image"><figure><img src="asset-original-assets-chapter-4-7.jpg" alt="Some visual clues"><figcaption>Some visual clues</figcaption></figure></section>')}};
window.chapterFour=chapterFour;

// Keep answers concealed until the player chooses the dedicated solution button.
chapterHints[0]=['<strong>Hint #1</strong><br>Take a close look at the back of the cryptic note. The message points straight to your first destination!'];
chapterHints[1][4]='<strong>Hint #5: The solved puzzle</strong><br>You now have enough information to identify the next destination. If you would prefer the answer, use the button below.';

// Chapter 2’s later visual resources stay hidden until the corresponding hint reveals them.
const chapterTwoWithImageTiming=chapterTwo;
chapterTwo=function(){chapterTwoWithImageTiming();document.querySelectorAll('img[src$="asset-original-assets-chapter-2-7.jpg"],img[src$="asset-original-assets-chapter-2-8.jpg"]').forEach(image=>{if(!image.closest('.hint-progress'))image.closest('figure')?.remove()})};
window.chapterTwo=chapterTwo;

// Correct the Chapter 1 resource captions to match the actual images.
Object.assign(imageLabels,{
  'c1-1.jpg':'The cryptic note (front)',
  'c1-2.jpg':'The cryptic note (back)',
  'c1-3.jpg':'Mr. Potato Head'
});
hintImages[0][0]=[['c1-2.jpg','The cryptic note (back)']];

// Never put a final answer in hint text; that is shown only after the player presses the solution button.
chapterHints[1][4]='<strong>Hint #5: The solved puzzle</strong><br>You now have enough information to identify the next destination. If you would prefer the answer, use the button below.';
chapterHints[2][2]='<strong>Hint #3: Put the letters in the correct order</strong><br>Work through the portraits from left to right, matching each person with the red letter on the folded family-tree clue. You now have enough information to identify the next destination. If you would prefer the answer, use the button below.';
chapterHints[3][5]='<strong>Hint #6: The solved puzzle</strong><br>You now have enough information to identify the house number on Williams Street. If you would prefer the answer, use the button below.';
chapterHints[4][3]='<strong>Hint #4: Solved puzzle</strong><br>You now have enough information to identify the palindrome. If you would prefer the answer, use the button below.';
chapterHints[5][3]='<strong>Hint #4: Colors</strong><br>Use the sequence of colors for the 5-letter code at the bottom of the clue to arrange the letters you extracted. You now have enough information to identify the final word. If you would prefer the answer, use the button below.';
chapterHints[6][3]='<strong>Hint #4</strong><br>You now have enough information to identify the 4-letter word. If you would prefer the answer, use the button below.';
chapterHints[7][3]='<strong>Hint #4: The Polaroid answers</strong><br>Identify each business and use the number on its Polaroid to select the corresponding letter. You now have enough information to identify the final answer. If you would prefer the answer, use the button below.';

// Older test runs may have saved revealed solutions. Clear that old state once so a fresh run never shows answers automatically.
if(localStorage.getItem('staff-ministry-solution-state-version')!=='2'){Object.keys(revealedSolutions).forEach(key=>delete revealedSolutions[key]);localStorage.setItem('staff-ministry-solutions',JSON.stringify(revealedSolutions));localStorage.setItem('staff-ministry-solution-state-version','2')}
function confirmRestartAdventure(){S.u=0;S.d=[];Object.keys(revealedHints).forEach(key=>delete revealedHints[key]);Object.keys(revealedSolutions).forEach(key=>delete revealedSolutions[key]);localStorage.setItem('staff-ministry-progress',JSON.stringify(S));localStorage.setItem('staff-ministry-hints',JSON.stringify(revealedHints));localStorage.setItem('staff-ministry-solutions',JSON.stringify(revealedSolutions));home()}
window.confirmRestartAdventure=confirmRestartAdventure;
