/* August revision: stable final layer for the requested story and navigation edits. */
(()=>{
const R={hint:JSON.parse(localStorage.getItem('staff-ministry-r1-hints')||'{}')};
const F=(s,l)=>`<figure><img src="${s}" alt="${l}"><figcaption>${l}</figcaption></figure>`;
const G=(...x)=>`<section class="gallery">${x.join('')}</section>`;
const nav=n=>`<div class="topline chapter-nav"><button class="button ghost" onclick="map()">← Case map</button><span class="small">Chapter ${n+1} of 8</span></div>`;
const remember=()=>localStorage.setItem('staff-ministry-r1-hints',JSON.stringify(R.hint));
const showAtBottom=()=>requestAnimationFrame(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'auto'}));
const c1Hints=[
`<strong>Hint #1: Examine the crime scene</strong><br>Take a close look at the back of the cryptic note left behind at Bliss Park. The message points straight to your very first destination!`,
`<strong>Hint #2: Go to the address mentioned in the back of the cryptic note.</strong>${G(F('asset-chapter1-new-fairfield-map.jpg','Location of Fairfield Terrace'))}`,
`<strong>Hint #3: The address</strong><br>Look for the house located at 14 Fairfield Terrace.${G(F('asset-chapter1-new-fairfield-map.jpg','Location of 14 Fairfield Terrace'))}`
];
function c1HintBox(){let n=R.hint.c1||0;let text=c1Hints.slice(0,n).map(x=>`<p>${x}</p>`).join('');let control=n<c1Hints.length?`<button class="button ghost full" onclick="r1MoreC1Hint()">${n?'Show another hint':'I need a hint'}</button>`:'<p class="small"><strong>No more hints available</strong></p>';return `<section class="hint-progress">${text}${control}</section>`}
function chapterOne(){app.innerHTML=wrap(`${nav(0)}<article class="card chapter original"><p class="location">📍 Bliss Park Playground</p><h3>THE STORY</h3><p>Back in 1716, the General Court granted 30 acres of <strong>“Ministry Land”</strong> to support Longmeadow’s first minister, Reverend Stephen Williams. What the early settlers never realized was that this land held an ancient secret: buried deep beneath the soil lay the <strong>Staff of Ministry</strong>, a magical relic of unknown origin that quietly kept the valley fertile and protected.</p><p>The staff remained completely lost and forgotten for over three centuries as the town grew. That is, until <strong>2026</strong>.</p><p>When excavation crews broke ground in Bliss Park to install the newly-renovated playground, they unearthed the strange, perfectly preserved wooden staff. Believing it to be a quirky piece of historical farm debris, the installation team whimsically incorporated it into the Mr. Potato Head statue's design, placing it right in Mr. Potato Head's hand. Unknowingly, they had awakened the ancient protection magic of the Green.</p>${G(F('asset-chapter1-new-form-image-1.jpg','Mr. Potato Head before the staff got stolen'))}<h3>THE CRIME</h3><p>Bliss Park, Longmeadow. 9:00 AM. The playground opens, but Mr. Potato Head is missing his staff. A <strong>cryptic note</strong> sits in its place.</p><p>The police are on-site but brush the missing staff story off. They dismiss it as nothing more than a local myth and a fantastic tale.</p><p>Suddenly, a woman approaches you. She introduces herself as <strong>Mrs. Orac</strong> from the <strong>Underground Longmeadow Historical Society</strong>. She desperately needs your help.</p><h3>YOUR MISSION</h3><p>Mrs. Orac warns that the thief has left <strong>a trail of clues</strong> tied to Longmeadow's history. You need to crack the clues and retrieve the relic before the Curse of 1716 is complete and the town of Longmeadow reverts to wilderness forever!</p>${G(F('c1-1.jpg','The thief’s cryptic note'),F('c1-2.jpg','The back of the thief’s cryptic note'))}<section class="answer"><h3>Did you find the star?</h3><button class="button full" onclick="r1Answer(0)">Yes and I know the star number!</button>${c1HintBox()}</section></article>`)}
window.r1MoreC1Hint=()=>{R.hint.c1=Math.min(3,(R.hint.c1||0)+1);remember();chapterOne();showAtBottom()};
function answer(n,label){app.innerHTML=wrap(`<section class="card answer"><p class="eyebrow">Submit your answer</p><h2>${label}</h2><input id="solution" class="solution" autocomplete="off" placeholder="Your answer"><button class="button full" onclick="r1Check(${n})">Submit answer</button><p id="feedback" class="small"></p><button class="button ghost" onclick="chapter(${n})">← Back to puzzle</button></section>`)}
window.r1Answer=n=>answer(n,n===0?'What is the star number?':'What is your answer?');
function johnny(){app.innerHTML=wrap(`${nav(0)}<article class="card chapter original"><h2>76 is right!</h2>${G(F('asset-chapter1-new-star.jpg','The star'))}<p>In front of the house marked with a star with the number 76, you find <strong>a crumpled note</strong>.</p>${G(F('asset-chapter1-new-crumpled-note.jpg','The crumpled note'))}<section class="answer"><h3><strong>Do you know the name of the boy who lived in the house with the numbered star during the late 18th century?</strong></h3><button class="button full" onclick="r1JohnnyAnswer()">Yes! I know the answer.</button><button class="button ghost full" onclick="r1JohnnyHint()">I need a hint</button><section id="johnny-hints" class="hint-progress"></section></section></article>`)}
window.r1JohnnyHint=()=>{const box=document.querySelector('#johnny-hints');if(box)box.innerHTML='<p><strong>Hint #1: The Legend of the Fruit</strong><br>The boy grew up to travel across America planting orchards of a crisp, delicious red fruit. Think of his famous nickname.</p><button class="button ghost full" onclick="r1JohnnyHint2()">Show another hint</button>'};
window.r1JohnnyHint2=()=>{const box=document.querySelector('#johnny-hints');if(box)box.innerHTML+='<p><strong>Hint #2: The “Hat” clue</strong><br>This folk hero wore a metal cooking pot on his head and became an iconic apple planter.</p><p><strong>Hint #3</strong><br>His legal name was John Chapman, but he is known by a six-letter nickname: J _ _ _ _ Y.</p>'};
window.r1JohnnyAnswer=()=>answer('johnny','What was the boy’s name?');
function mark(n){if(!S.d.includes(n))S.d.push(n);S.u=Math.max(S.u,Math.min(7,n+1));save()}
function c1Complete(){mark(0);app.innerHTML=wrap(`<section class="card chapter original"><div class="sigil">✓</div><p class="eyebrow">ANSWER ACCEPTED</p><h2>Correct! Johnny Appleseed once lived in this house!</h2><p>“Johnny Appleseed” (born John Chapman) was an American pioneer and nurseryman who became a legendary folk hero of the 19th century. Far from just casually scattering seeds, he strategically established formal apple tree nurseries across the American frontier, with his saplings primarily providing apples for hard cider — a crucial beverage of the era. With deep ties to the Massachusetts region, a young John Chapman even lived in Longmeadow's oldest standing home at <strong>14 Fairfield Terrace</strong> after his family moved to town in 1780.</p>${G(F('asset-chapter1-new-johnny-appleseed.jpg','Johnny Appleseed'))}<aside class="clue"><h3>Did you know?</h3><p>The historic house located at <strong>14 Fairfield Terrace</strong> holds the title of being the oldest standing structure in Longmeadow?</p><p><strong>1. Built in the Meadows (Before 1700)</strong><br>The house was originally built down in the fertile lowlands along the Connecticut River (the “meadows”). During this early period, the entire settlement of Longmeadow was concentrated in this low-lying floodplain.</p><p><strong>2. Moved to the Hill (1700)</strong><br>Living in the lowlands came with a major hazard: devastating seasonal floods. After a particularly disastrous flood in 1695, the townspeople decided it was time to abandon the floodplain. In <strong>1700</strong>, the house was physically moved up the hill to the “upper terrace.” This is where a young John Chapman later lived with his family after they moved to town in 1780.</p><p><strong>3. Moved to its Present Location (1913)</strong><br>As the town modernized and suburban subdivisions began expanding at the turn of the 20th century, the house was moved a final time. In <strong>1913</strong>, it was relocated to its current resting spot on <strong>14 Fairfield Terrace</strong>.</p></aside><p>While you marvel at the incredible feat of moving a historic house three times, your phone buzzes with <strong>a message from Mrs. Orac.</strong> She is also kind enough to send you the location of Harold Grinspoon's <strong>sculpture.</strong></p>${G(F('asset-chapter1-new-orac-message.jpg','Message from Mrs. Orac'),F('asset-chapter1-new-grinspoon-map.jpg','Location of Harold Grinspoon’s sculpture'),F('asset-original-assets-chapter-2-3.jpg','Harold Grinspoon ‘Life’ Sculpture'))}<p>Head toward the sculpture to continue the adventure.</p><button class="button full" onclick="map()">Open case map</button></section>`)}
window.r1Check=n=>{const value=(document.querySelector('#solution')?.value||'').toLowerCase().replace(/[^a-z0-9]/g,'');if(n===0){if(value==='76')johnny();else document.querySelector('#feedback').textContent='Incorrect. Review the clue and try again.';return}if(n==='johnny'){if(value==='johnny'||value==='john')c1Complete();else document.querySelector('#feedback').textContent='Incorrect. Review the hints and try again.';return}window.checkAnswer(n)};

const oldChapter=window.chapter,oldHome=window.home,oldMap=window.map;
window.chapter=n=>{if(n===0)return chapterOne();oldChapter(n);requestAnimationFrame(()=>tune(n))};
function tune(n){const article=document.querySelector('.chapter');if(!article)return;article.querySelectorAll('p').forEach(p=>{p.innerHTML=p.innerHTML.replace(/a slip of paper wedged into the bench frame\.?/i,'<strong>a slip of paper wedged into the bench frame.</strong>').replace(/two enigmatic papers/i,'<strong>two enigmatic papers</strong>').replace(/folded slip of paper/i,'<strong>folded slip of paper</strong>').replace(/a stack of pictures/ig,'<strong>a stack of pictures</strong>').replace(/your final test/ig,'<strong>your final test</strong>')});const loc=article.querySelector('.location');if(loc){const v=['','Start at the Harold Grinspoon’s ‘Life’ sculpture.','Start at the Storrs Library.','Start at the First Church of Christ.','Start at 20 Williams Street.','Start at the Ann Scibelli’s Memorial.','Start at the Razzmatazz Kids toy store.','Start at the Longmeadow Shops — North side of Bliss Road.'];if(v[n])loc.textContent='📍 '+v[n]}
const removeExtra=(caption,keep=1)=>{[...article.querySelectorAll('figure')].filter(x=>x.querySelector('figcaption')?.textContent.trim()===caption).slice(keep).forEach(x=>x.remove())};
if(n===1){article.querySelectorAll('p').forEach(x=>{if(/^Start at the Harold/i.test(x.textContent))x.remove()});removeExtra('Location of the sculpture',0);removeExtra('The view from where the clue was left',1);article.querySelectorAll('.hint-progress figure').forEach(x=>{if(x.textContent.includes('The clue left in front of the sculpture'))x.remove()})}
if(n===2){removeExtra('Location of the Storrs Library',1);const buttons=article.querySelectorAll('.answer .button');if(buttons[0])buttons[0].textContent='Yes, I can enter the library.';if(buttons[1])buttons[1].textContent='No, the library is closed.'}
if(n===3){removeExtra('First Church of Christ',1);removeExtra('Location of the First Church of Christ',1);article.querySelectorAll('.hint-progress p').forEach(x=>x.innerHTML=x.innerHTML.replace(/Plaques on War$/,'Plaques on War memorial'))}
if(n===4){removeExtra('Location of 20 Williams street',1);removeExtra('20 Williams street',1);article.querySelectorAll('figure').forEach(x=>{if(x.textContent.includes('The scroll pediment at 20 Williams Street')&&!x.closest('.hint-progress'))x.remove()})}
if(n===5){article.querySelectorAll('figure').forEach(x=>{if(x.textContent.includes('Ann Scibelli’s Memorial')&&x.closest('.hint-progress'))x.querySelector('figcaption').textContent='The memorial plaque'})}
if(n===6){removeExtra('Location of Razzmatazz Kids',1);removeExtra('Razzmatazz Kids storefront',1);article.querySelectorAll('.hint-progress figure').forEach(x=>{if(x.textContent.includes('The Longmeadow trolley'))x.remove()})}
if(n===7){removeExtra('Location of the Longmeadow Shops on the North side of Bliss road',1);removeExtra('The Longmeadow Shops',1);article.innerHTML=article.innerHTML.replace(/Bliss road/g,'Bliss Road')}
}
window.home=()=>{oldHome();const card=document.querySelector('.card.original');if(!card)return;const p=[...card.querySelectorAll('p')].find(x=>x.textContent.includes('built this interactive mystery trail'));if(p)p.insertAdjacentHTML('afterend','<p>This adventure is completely free to enjoy! If you have a great time and would like to support our family in creating more local games, a contribution via <a href="https://www.venmo.com/u/CarohartMA" target="_blank" rel="noopener">Venmo</a> at @CarohartMA is always appreciated (but never expected!). We hope you enjoy it!<br>&nbsp;🂵 The 5 of H(e)arts</p>')};
window.map=()=>{oldMap();document.querySelectorAll('.stop small').forEach(x=>{if(x.textContent==='20 Williams')x.textContent='20 Williams Street';if(x.textContent==='Ann Scibelli’s memorial')x.textContent='Ann Scibelli’s Memorial'})};
window.home();
})();

