function completeChapter(n){if(!S.d.includes(n))S.d.push(n);S.u=Math.max(S.u,Math.min(7,n+1));save();app.innerHTML=wrap(`<section class="card complete"><div class="sigil">✓</div><p class="eyebrow">Answer accepted</p><h2>Correct!</h2><p>You are ready to move onto the next chapter.</p><button class="button" onclick="map()">Open case map</button></section>`)}
function checkAnswer(n){const entered=document.querySelector('#solution').value.toLowerCase().replace(/[^a-z0-9]/g,'');if(!entered.includes(answerRules[n][1])){document.querySelector('#feedback').textContent='Incorrect. Review the clue and open the hint room, then try again.';return}if(n===4){chapterFiveRacecar();return}completeChapter(n)}window.checkAnswer=checkAnswer;window.completeChapter=completeChapter;

// Preserve the full original ending material for the final two chapters.
const baseCompleteChapter=completeChapter;
completeChapter=function(n){
  if(n===6){if(!S.d.includes(n))S.d.push(n);S.u=Math.max(S.u,7);save();app.innerHTML=wrap(`<section class="card chapter original"><div class="sigil">✓</div><p class="eyebrow">Answer accepted</p><h2>Correct! You are ready to move onto the next chapter.</h2><p>Back in 1896, long before cars filled Route 5, electric trolleys (or trams) rattled straight down Longmeadow Street. Powered by overhead wires, these wooden streetcars were famous for the sharp “Ding! Ding!” of their brass foot-gongs, warning horses and pedestrians to make way.</p><p>The line ran all the way down to the Connecticut state border, where passengers would hop off at “Sharkey’s State Line House”—a legendary waiting room famous for hot dogs and dancing—to transfer to the Hartford line. For over forty years, these trolleys were the heartbeat of town travel until the last tracks faded around 1940!</p><p>Your thoughts wander to the past, imagining what it would have felt like to glide down Route 5 on an old electric tram with your friends. Suddenly, a panicked message from Mrs. Orac snaps you back to the present.</p><section class="gallery"><figure><img src="asset-original-assets-chapter-7-7.jpg" alt="The Longmeadow trolley"><figcaption>The Longmeadow trolley</figcaption></figure><figure><img src="asset-original-assets-chapter-7-9.jpg" alt="Panicked message from Mrs. Orac"><figcaption>Panicked message from Mrs. Orac</figcaption></figure></section><p><strong>Head toward the Longmeadow Shops on the north side of Bliss Road.</strong></p><button class="button" onclick="map()">Open case map</button></section>`);return}
  if(n===7){if(!S.d.includes(n))S.d.push(n);S.u=7;save();app.innerHTML=wrap(`<section class="card chapter original"><div class="sigil">✓</div><p class="eyebrow">Final answer accepted</p><h2>Ice cream was the final clue?!</h2><p>You head toward the local ice cream shop — <strong>Batch Ice Cream (682A Bliss Rd)</strong> — expecting to find the rogue historian ready to surrender the Staff of Ministry.</p><p>Instead, you find Mrs. Orac smiling ear-to-ear while enjoying a scoop. But she isn't just smiling because of the ice cream—she’s smiling because of you! Looking around, you spot the very race car you’d been chasing earlier, safely parked right out front. What in the world?!</p><p>As you stand there confused, Mrs. Orac invites you to take a seat and reveals the truth: it was all a test!</p><p>The Staff of Ministry was pure fiction (though all the fascinating Longmeadow history you uncovered along the way was <strong>100% real!</strong>). Longmeadow was never under the Curse of 1716, and there was no actual thief—just Mrs. Orac dropping clues all over town to test your skills!</p><p>As a member of the Underground Longmeadow Historical Society, she designed this challenge to recruit the sharpest minds in town—the Master Detectives Longmeadow can count on when real mysteries arise.</p><p>You’ve proven your brilliance, teamwork, and quick thinking. Take a bow—you are officially <strong>certified Underground Longmeadow Historical Society members!</strong></p><section class="gallery"><figure><img src="asset-original-assets-chapter-8-6.jpg" alt="Ice cream was the coolest reward in town"><figcaption>Ice cream was the “coolest” reward in town!</figcaption></figure></section><button class="button" onclick="home()">Return to main menu</button></section>`);return}
  baseCompleteChapter(n)
};
window.completeChapter=completeChapter;

const completeWithUpdatedTipText=completeChapter;
completeChapter=function(n){completeWithUpdatedTipText(n);if(n===7){const supportLine=[...document.querySelectorAll('.chapter.original p')].find(p=>p.textContent.includes('Help us create more games.'));if(supportLine)supportLine.innerHTML='<strong>Help us create more games.</strong> Thanks for playing! If you enjoyed the game and want to support me making more local adventures like this, feel free to add an optional tip.'}};
window.completeChapter=completeChapter;

// Final reward screen: include the original badge, certificate, and optional support link.
const completeWithFinalReward=completeChapter;
completeChapter=function(n){if(n!==7)return completeWithFinalReward(n);if(!S.d.includes(n))S.d.push(n);S.u=7;save();app.innerHTML=wrap(`<section class="card chapter original"><div class="sigil">✓</div><p class="eyebrow">Final answer accepted</p><h2>Ice cream was the final clue?!</h2><p>You head toward the local ice cream shop — <strong>Batch Ice Cream (682A Bliss Rd)</strong> — expecting to find the rogue historian ready to surrender the Staff of Ministry.</p><p>Instead, you find Mrs. Orac smiling ear-to-ear while enjoying a scoop. But she isn't just smiling because of the ice cream—she’s smiling because of you! Looking around, you spot the very race car you’d been chasing earlier, safely parked right out front. What in the world?!</p><p>As you stand there confused, Mrs. Orac invites you to take a seat and reveals the truth: it was all a test!</p><p>The Staff of Ministry was pure fiction (though all the fascinating Longmeadow history you uncovered along the way was <strong>100% real!</strong>). Longmeadow was never under the Curse of 1716, and there was no actual thief—just Mrs. Orac dropping clues all over town to test your skills!</p><p>As a member of the Underground Longmeadow Historical Society, she designed this challenge to recruit the sharpest minds in town—the Master Detectives Longmeadow can count on when real mysteries arise.</p><p>You’ve proven your brilliance, teamwork, and quick thinking. Take a bow—you are officially <strong>certified Underground Longmeadow Historical Society members!</strong></p><section class="gallery"><figure><img src="asset-original-assets-chapter-8-6.jpg" alt="Ice cream was the coolest reward in town"><figcaption>Ice cream was the “coolest” reward in town!</figcaption></figure><figure><img src="asset-original-assets-chapter-8-7.jpg" alt="Your badge of honor"><figcaption>Your badge of honor!</figcaption></figure><figure><img src="asset-original-assets-chapter-8-8.jpg" alt="Your official certificate"><figcaption>Your official certificate</figcaption></figure></section><p><strong>Help us create more games.</strong> Thanks for playing! If you enjoyed the game and want to support our family's outdoor adventures, tips are appreciated (optional).</p><a class="button full" href="https://www.venmo.com/u/CarohartMA" target="_blank" rel="noopener">Optional tip via Venmo</a><button class="button ghost full" onclick="home()">Return to main menu</button></section>`)};
window.completeChapter=completeChapter;
